; Tile index $000
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $001
.db $AD $FF $52 $FF $AA $FF $55 $FF $25 $FF $DA $FF $AA $FF $55 $FF $4B $FF $B4 $FF $D6 $FF $29 $FF $5B $FF $A4 $FF $BF $FF $40 $FF
; Tile index $002
.db $B7 $FF $48 $FF $DA $FF $25 $FF $55 $FF $AA $FF $DD $FF $22 $FF $B5 $FF $4A $FF $EE $FF $11 $FF $B9 $FF $46 $FF $ED $FF $12 $FF
; Tile index $003
.db $FF $FF $00 $FF $AA $FF $55 $FF $55 $FF $AA $FF $AA $FF $55 $FF $54 $FF $AB $FF $AA $FF $55 $FF $55 $FF $AA $FF $56 $FF $A9 $FF
; Tile index $004
.db $FF $FF $00 $FF $B6 $FF $49 $FF $6F $FF $90 $FF $AB $FF $54 $FF $AE $FF $51 $FF $AF $FF $50 $FF $B5 $FF $4A $FF $BF $FF $40 $FF
; Tile index $005
.db $FF $FF $00 $FF $FF $FF $00 $FF $BF $FF $40 $FF $F7 $FF $08 $FF $FF $FF $00 $FF $ED $FF $12 $FF $FC $FC $03 $FF $F0 $FF $0F $FF
; Tile index $006
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $F2 $F2 $0D $FF $00 $00 $FF $FF $02 $E5 $FF $FD
; Tile index $007
.db $EB $EB $14 $FF $EF $EF $10 $FF $FF $FF $00 $FF $DF $DF $20 $FF $7F $7F $80 $FF $FF $FF $00 $FF $1F $1F $E0 $FF $5F $BE $E1 $BE
; Tile index $008
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FB $FF $04 $FF $EF $F4 $1B $FF $BC $FB $47 $FF $B6 $80 $74 $FF $D3 $68 $BB $7C
; Tile index $009
.db $FE $FE $01 $FF $FF $FF $00 $FF $FE $E9 $17 $FF $DA $B6 $6E $FD $60 $11 $71 $FF $FF $70 $FF $80 $FF $01 $FE $00 $EE $74 $6E $61
; Tile index $00A
.db $93 $93 $6C $FF $F4 $4A $BE $FF $2D $7D $7D $D2 $12 $BD $BF $ED $FF $80 $FF $00 $FF $BF $48 $08 $FF $14 $EB $00 $FD $F8 $3D $3A
; Tile index $00B
.db $FF $00 $FF $FF $00 $AA $AA $FF $BF $F2 $FF $40 $E0 $51 $F1 $1F $FE $2E $FE $01 $EF $01 $EE $10 $F7 $08 $FF $00 $3F $9F $20 $C0
; Tile index $00C
.db $FF $12 $ED $FF $01 $AB $AB $FE $B7 $6D $FF $48 $5C $62 $7E $A3 $63 $22 $63 $9C $FF $01 $FF $00 $D9 $01 $D9 $26 $FF $9B $65 $01
; Tile index $00D
.db $EF $10 $FF $FF $11 $AB $AB $FE $36 $B5 $B7 $C9 $D8 $60 $F8 $27 $40 $04 $44 $BF $B2 $63 $F3 $4D $45 $01 $45 $BA $D0 $88 $D8 $AF
; Tile index $00E
.db $FB $00 $FB $FF $01 $49 $49 $FE $06 $00 $06 $F9 $06 $40 $46 $FB $12 $12 $12 $ED $C4 $D4 $D4 $3B $00 $00 $00 $FF $F4 $40 $B4 $9F
; Tile index $00F
.db $A0 $6A $6A $DF $60 $C1 $E1 $BF $02 $08 $0A $FF $08 $40 $48 $FF $54 $01 $15 $FF $22 $80 $A2 $FD $04 $02 $02 $FF $3F $04 $3F $C4
; Tile index $010
.db $B2 $48 $EA $FF $01 $13 $13 $FE $00 $44 $44 $FF $01 $12 $13 $FF $20 $44 $64 $FF $AF $10 $BF $FF $03 $00 $03 $FF $C1 $2A $EB $3E
; Tile index $011
.db $B7 $4D $FA $FF $1F $A2 $BD $FF $BF $47 $F8 $FF $EB $1D $F6 $FF $5F $AB $F4 $FF $17 $4E $59 $FF $D0 $00 $FF $FF $FF $30 $FF $00
; Tile index $012
.db $80 $80 $7F $FF $C0 $C0 $3F $FF $80 $80 $7F $FF $C0 $C0 $3F $FF $40 $40 $BF $FF $92 $92 $6D $FF $20 $20 $DF $FF $66 $C9 $BF $F9
; Tile index $013
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $02 $02 $FD $FF $41 $41 $BE $FF $10 $00 $FF $FF $D3 $54 $AF $7C
; Tile index $014
.db $02 $02 $FD $FF $2E $2E $D1 $FF $09 $09 $F6 $FF $BB $BB $44 $FF $22 $22 $DD $FF $13 $13 $EC $FF $1F $1F $E0 $FF $5F $FF $E0 $FF
; Tile index $015
.db $DC $DC $23 $FF $FF $FF $00 $FF $7F $7F $80 $FF $FF $FF $00 $FF $FD $FD $02 $FF $FD $FD $02 $FF $FD $FD $02 $FF $FE $FE $01 $FF
; Tile index $016
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $56 $56 $A9 $FF $50 $50 $AF $FF $0A $0A $F5 $FF $55 $55 $AA $FF $4A $4A $B5 $FF
; Tile index $017
.db $05 $05 $FA $FF $7B $7B $84 $FF $9F $9F $60 $FF $FF $FF $00 $FF $AF $AF $50 $FF $FF $FF $00 $FF $55 $55 $AA $FF $BF $BF $40 $FF
; Tile index $018
.db $FF $FF $00 $FF $FF $FF $00 $FF $FB $FF $04 $FF $EE $FF $11 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $7F $7F $80 $FF
; Tile index $019
.db $D5 $FF $2A $FF $DF $FF $20 $FF $B1 $FF $4F $FF $E8 $FF $17 $FF $55 $FF $AF $FF $D8 $FF $27 $FF $B0 $FF $4F $FF $C9 $FF $37 $FF
; Tile index $01A
.db $55 $FF $AA $FF $FF $FF $00 $FF $24 $FF $FF $FF $00 $FF $FF $FF $10 $FF $FF $FF $49 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $01B
.db $55 $FF $AA $FF $FF $FF $00 $FF $91 $FE $FF $FE $00 $FF $FF $FF $00 $FF $FF $FF $04 $FF $FF $FF $00 $FF $FF $FF $04 $FF $FF $FF
; Tile index $01C
.db $CB $FF $34 $FF $BF $FF $40 $FF $13 $EF $FC $EF $03 $FF $FC $FF $03 $FF $FC $FF $83 $FF $FC $FF $07 $FF $F8 $FF $93 $FF $FC $FF
; Tile index $01D
.db $F7 $FC $0C $FC $F9 $F8 $06 $FC $7F $FE $80 $FE $FF $FD $03 $FE $FF $FF $00 $FF $FE $FE $01 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $01E
.db $AB $0C $76 $3C $43 $80 $7C $7E $9B $03 $7F $3F $E4 $03 $3D $3D $F4 $22 $3D $39 $F0 $86 $9B $1B $E5 $88 $1B $8B $F5 $CC $47 $87
; Tile index $01F
.db $CF $0D $73 $3F $93 $82 $7E $FC $7D $07 $F9 $FD $7E $30 $CD $F9 $66 $52 $B3 $F9 $EF $5B $BB $F3 $D7 $0C $D6 $F7 $BF $61 $F7 $C6
; Tile index $020
.db $C7 $0D $0A $70 $EE $51 $7F $60 $ED $07 $0F $30 $5F $A4 $0F $10 $FF $80 $8F $90 $6A $9F $0E $01 $B3 $03 $C3 $8C $F7 $CB $C3 $04
; Tile index $021
.db $3F $CE $87 $00 $BB $C5 $C1 $02 $AF $92 $C3 $03 $56 $B9 $D0 $00 $FF $C8 $C8 $10 $7D $4E $5C $90 $7C $43 $42 $9C $FE $C7 $DF $18
; Tile index $022
.db $EC $10 $C4 $0F $71 $30 $49 $CE $3F $35 $2A $E8 $FE $B0 $FE $39 $B8 $33 $88 $4F $1F $70 $4F $08 $ED $02 $17 $08 $68 $97 $08 $0F
; Tile index $023
.db $1E $A1 $38 $C0 $FE $78 $81 $00 $F6 $59 $A9 $00 $F2 $0D $F0 $08 $C7 $38 $D8 $20 $F2 $0D $F0 $08 $56 $B8 $51 $A8 $52 $8D $50 $A8
; Tile index $024
.db $FE $89 $F0 $40 $BF $60 $98 $81 $76 $29 $78 $81 $FE $71 $79 $80 $4F $B0 $00 $01 $9E $08 $09 $F0 $77 $69 $E9 $90 $D6 $60 $F9 $A0
; Tile index $025
.db $C1 $20 $E1 $FF $B6 $06 $B6 $C9 $7F $12 $7F $80 $F6 $49 $3E $80 $4B $30 $7E $80 $AF $4A $74 $80 $FF $84 $F9 $00 $FF $18 $69 $89
; Tile index $026
.db $DB $A8 $8B $14 $E7 $98 $1F $00 $BF $40 $07 $08 $FC $87 $CF $C3 $DF $22 $47 $C4 $19 $E1 $05 $02 $EE $10 $E2 $E3 $EF $42 $71 $C1
; Tile index $027
.db $F6 $69 $F0 $00 $7E $C9 $E9 $90 $96 $89 $88 $71 $7E $09 $79 $80 $F7 $11 $F9 $00 $8E $08 $89 $70 $1E $49 $49 $F0 $0E $08 $09 $F0
; Tile index $028
.db $C0 $92 $D2 $7F $41 $12 $93 $FF $D0 $10 $D0 $AF $FC $88 $FC $03 $7F $07 $7F $80 $EF $6B $6F $90 $DA $07 $5F $A5 $F4 $68 $74 $C7
; Tile index $029
.db $7D $42 $4F $C2 $F3 $40 $C7 $8F $BF $00 $CF $8E $FF $48 $4E $86 $F3 $4E $42 $82 $F2 $C1 $CE $06 $BF $83 $C5 $0F $F3 $40 $4F $87
; Tile index $02A
.db $DB $16 $6E $7E $9A $C9 $F6 $FE $9E $1B $E4 $7E $BF $9C $62 $FE $7F $BF $C1 $FF $9D $BE $62 $FE $B7 $3E $88 $7E $DB $5C $E6 $7E
; Tile index $02B
.db $B9 $47 $3F $3F $D1 $20 $1F $1E $6D $91 $0F $0F $FC $CD $CB $0F $7B $E4 $A3 $E2 $7D $D3 $B1 $F0 $FF $F8 $88 $78 $7B $D8 $A4 $F8
; Tile index $02C
.db $8F $4F $70 $7F $87 $87 $F8 $FF $95 $85 $FA $FF $BF $9F $E0 $FF $3F $BF $40 $7F $BF $AF $D0 $FF $7F $BF $40 $7F $3F $AF $50 $7F
; Tile index $02D
.db $FB $FB $04 $FF $F0 $F0 $0F $FF $80 $FF $7F $FF $C0 $FF $3F $FF $E0 $DF $3F $DF $B8 $C7 $7F $C7 $C8 $FF $37 $FF $80 $FF $7F $FF
; Tile index $02E
.db $6F $6F $90 $FF $00 $00 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $0C $FF $F3 $FF $EF $14 $FB $14 $EB $FF $14 $FF $41 $BE $FF $BE
; Tile index $02F
.db $FF $FF $00 $FF $35 $35 $CA $FF $42 $BD $FF $BD $40 $FF $BF $FF $12 $FF $ED $FF $EC $93 $7F $93 $FF $FF $00 $FF $24 $DB $FF $DB
; Tile index $030
.db $FF $FF $00 $FF $BF $BF $40 $FF $1F $FF $E0 $FF $3B $FF $C4 $FF $9F $FF $60 $FF $BF $7F $C0 $7F $BF $FF $40 $FF $9E $7E $E1 $7F
; Tile index $031
.db $B0 $FF $4F $FF $D4 $FF $2B $FF $AB $FF $54 $FF $D6 $FF $29 $FF $AB $FF $54 $FF $FF $FF $00 $FF $AF $FF $50 $FF $FF $FF $00 $FF
; Tile index $032
.db $00 $FF $FF $FF $2A $FF $D5 $FF $FF $FF $00 $FF $FE $FF $01 $FF $FF $FF $00 $FF $FD $FF $02 $FF $FF $FF $00 $FF $FA $FF $05 $FF
; Tile index $033
.db $00 $FF $FF $FF $8B $FF $74 $FF $FF $FF $00 $FF $BF $FF $40 $FF $FF $FF $00 $FF $5F $FF $A0 $FF $FF $FF $00 $FF $FC $FC $03 $FF
; Tile index $034
.db $1F $FF $E0 $FF $FF $FF $00 $FF $FE $FE $01 $FF $FF $FF $00 $FF $F7 $F7 $08 $FF $DF $DF $20 $FF $2F $2F $D0 $FF $DF $DF $20 $FF
; Tile index $035
.db $FF $FF $00 $FF $BF $AF $50 $FF $FF $FB $04 $FF $FF $F7 $08 $FF $7D $7F $82 $FF $FF $F7 $08 $FF $FB $FD $06 $FF $F7 $DE $29 $FF
; Tile index $036
.db $FA $E1 $27 $E7 $FB $6B $AF $CC $FF $F0 $17 $FC $EB $50 $9F $F8 $DE $75 $BF $E4 $6E $DB $9F $F8 $BD $66 $FF $C0 $3B $C5 $FE $C0
; Tile index $037
.db $8F $FA $EF $2C $F7 $AD $E7 $24 $FF $00 $DC $3F $FF $70 $FF $00 $BD $C2 $FF $00 $DD $22 $FF $00 $73 $B1 $CF $00 $EB $63 $9E $00
; Tile index $038
.db $DF $E7 $C7 $00 $43 $FF $C3 $42 $BF $40 $C1 $3F $BF $79 $F9 $06 $7B $F8 $FB $04 $F7 $DB $FF $08 $FF $BE $FF $00 $BE $72 $FE $01
; Tile index $039
.db $7F $C7 $C7 $98 $AF $D9 $8D $8A $77 $01 $73 $FE $FB $9E $DE $25 $F5 $F7 $F7 $0A $61 $F1 $F1 $9E $B4 $CE $CE $7B $2D $0C $0D $F3
; Tile index $03A
.db $29 $C0 $99 $0E $CA $F4 $CA $0D $CC $F0 $FC $0B $70 $F1 $F1 $8F $84 $50 $D4 $7B $44 $C1 $C5 $BF $A0 $00 $20 $FF $43 $0B $4B $FC
; Tile index $03B
.db $16 $39 $18 $E0 $B0 $4F $B0 $40 $3F $32 $3A $CD $DE $2B $FF $20 $07 $1F $0F $F8 $1A $17 $1F $E5 $37 $17 $37 $C8 $89 $09 $89 $76
; Tile index $03C
.db $E6 $00 $F9 $80 $74 $FB $70 $50 $BF $75 $7F $CA $FD $40 $FF $00 $FF $40 $FF $00 $F7 $BF $FF $08 $DF $FC $FF $20 $3F $B2 $BF $C0
; Tile index $03D
.db $EE $B0 $AB $21 $7F $D3 $63 $43 $3D $43 $7B $CE $FF $07 $F9 $01 $FF $1F $EF $0F $FF $3F $CF $0F $FF $2D $D2 $00 $FF $00 $FF $00
; Tile index $03E
.db $EF $F1 $E1 $E0 $E0 $FF $E0 $E0 $FF $02 $D3 $8D $FF $E9 $FF $E9 $FF $D6 $FF $D6 $FD $C2 $FF $C2 $FF $24 $DF $00 $EF $13 $FF $00
; Tile index $03F
.db $F7 $39 $F1 $01 $50 $DF $70 $50 $5F $30 $7A $EF $F7 $3F $FF $08 $FD $6E $FF $6B $B7 $69 $FF $48 $EF $BC $FF $10 $13 $B6 $B7 $EC
; Tile index $040
.db $BE $48 $26 $85 $5F $A0 $0F $04 $E3 $31 $F3 $DC $7F $C6 $FF $80 $CF $E1 $EF $30 $2F $B8 $BF $D0 $CE $40 $CE $31 $C7 $02 $C7 $3A
; Tile index $041
.db $B7 $02 $4F $85 $02 $FF $02 $02 $6F $95 $FA $FF $FF $E0 $FB $1F $AF $7C $F9 $57 $FF $72 $FF $0D $FA $C9 $F9 $47 $FA $8E $FE $05
; Tile index $042
.db $DF $4E $F0 $7E $D7 $4F $7F $7F $1F $1F $E0 $FF $FF $1E $61 $FF $3D $AF $92 $FF $BF $2F $90 $FF $DD $2F $32 $FF $5F $2F $70 $FF
; Tile index $043
.db $6F $7E $92 $7E $DF $FF $E1 $FF $FF $FF $00 $FF $BF $FF $40 $FF $FF $FF $00 $FF $7F $FF $80 $FF $FF $FF $00 $FF $FF $FE $01 $FF
; Tile index $044
.db $7F $DF $20 $7F $7D $EF $12 $7F $CF $5F $B0 $7F $FF $DF $20 $FF $FF $FF $00 $FF $FC $FC $03 $FF $E6 $E6 $19 $FF $E9 $E9 $16 $FF
; Tile index $045
.db $F7 $FF $08 $FF $FF $FF $00 $FF $FB $FB $04 $FF $E0 $E0 $1F $FF $58 $58 $A7 $FF $A8 $A8 $57 $FF $44 $44 $BB $FF $35 $35 $CA $FF
; Tile index $046
.db $FB $FF $04 $FF $FF $FF $00 $FF $FD $FD $02 $FF $01 $01 $FE $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $5F $5F $A0 $FF
; Tile index $047
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $5E $5E $A1 $FF $77 $77 $88 $FF $AE $AE $51 $FF $5B $5B $A4 $FF
; Tile index $048
.db $EF $EF $10 $FF $FC $FC $03 $FF $D3 $D3 $2C $FF $AD $AD $52 $FF $EA $EA $15 $FF $FF $FF $00 $FF $FA $FA $05 $FF $5F $5F $A0 $FF
; Tile index $049
.db $FF $FF $00 $FF $7D $7F $82 $FF $FF $FF $00 $FF $FB $FF $04 $FF $FD $FF $02 $FF $DB $FF $24 $FF $FF $FF $00 $FF $DD $FF $22 $FF
; Tile index $04A
.db $FF $FF $00 $FF $5F $FF $A0 $FF $FD $FF $02 $FF $6F $FF $90 $FF $BF $FF $40 $FF $EF $FF $10 $FF $BF $FF $40 $FF $FB $FF $04 $FF
; Tile index $04B
.db $FD $FD $02 $FF $FD $FD $02 $FF $F7 $F7 $08 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $BF $FF $40 $FF $F6 $FF $09 $FF
; Tile index $04C
.db $7F $7F $80 $FF $7E $7F $81 $FF $7F $7F $80 $FF $FD $FF $02 $FF $F6 $FF $09 $FF $FD $EF $12 $FF $EE $FF $11 $FF $FB $FE $05 $FF
; Tile index $04D
.db $D6 $FD $29 $FF $B9 $F7 $4F $FE $F7 $EE $1B $FC $2B $D4 $FF $FC $D7 $7C $AF $F8 $AD $D2 $77 $FA $D7 $A9 $7E $F8 $AF $D9 $7E $F0
; Tile index $04E
.db $B7 $09 $FE $00 $F7 $87 $F8 $80 $FF $66 $D9 $40 $AF $4E $B3 $02 $FF $EF $5A $4A $3F $EB $15 $01 $FF $FD $E3 $E1 $9F $F5 $9A $90
; Tile index $04F
.db $F7 $E3 $1C $00 $F7 $C6 $39 $00 $FF $BC $43 $00 $FE $DD $22 $01 $FD $FA $05 $02 $FE $F9 $67 $60 $FD $7A $A5 $22 $FF $F0 $AF $A0
; Tile index $050
.db $BD $0C $BD $43 $F0 $DA $FA $0F $E4 $C0 $E4 $1F $C0 $00 $C0 $3F $48 $80 $48 $BF $80 $41 $81 $7F $84 $00 $84 $7F $00 $C0 $00 $FF
; Tile index $051
.db $54 $38 $3C $EF $01 $42 $42 $FF $C6 $40 $C4 $BF $19 $20 $29 $FF $02 $00 $02 $FF $14 $18 $18 $EF $22 $20 $22 $DF $04 $00 $00 $FF
; Tile index $052
.db $80 $00 $80 $FF $01 $A4 $A5 $FF $E8 $00 $88 $FF $60 $00 $20 $FF $8C $00 $0C $F3 $38 $20 $38 $C7 $E9 $12 $61 $9F $60 $40 $60 $9F
; Tile index $053
.db $00 $04 $04 $FF $48 $10 $50 $FF $00 $01 $01 $FF $83 $24 $A6 $7F $0C $00 $08 $FF $02 $00 $02 $FF $02 $08 $0A $FF $15 $00 $15 $FF
; Tile index $054
.db $7F $75 $7F $80 $01 $A1 $A1 $FE $80 $05 $05 $FF $51 $00 $50 $FF $AB $00 $AB $FF $FE $00 $FC $FF $A9 $00 $89 $FF $60 $00 $60 $FF
; Tile index $055
.db $DB $A4 $DB $24 $A4 $89 $A4 $5B $00 $00 $00 $FF $40 $00 $40 $FF $A8 $00 $A8 $FF $00 $04 $04 $FF $44 $00 $40 $FF $02 $01 $02 $FD
; Tile index $056
.db $9C $54 $9C $63 $23 $03 $23 $DC $1B $19 $1B $E4 $55 $00 $55 $AA $02 $05 $07 $F8 $1B $05 $1E $E0 $22 $52 $3D $C0 $C8 $20 $FF $00
; Tile index $057
.db $02 $03 $03 $FD $F7 $DC $FF $08 $FF $E0 $FF $00 $FF $11 $FF $01 $FF $1A $E5 $00 $D3 $FE $01 $00 $FE $FF $00 $00 $7F $7F $80 $00
; Tile index $058
.db $E7 $8B $EC $18 $FB $01 $F2 $0C $F3 $C0 $73 $4C $DB $32 $CB $04 $79 $AA $53 $04 $FD $58 $A5 $02 $FD $AA $57 $00 $D0 $E7 $3F $00
; Tile index $059
.db $F9 $19 $F9 $16 $DB $A3 $7B $04 $DE $AE $7E $01 $D6 $CC $1E $21 $DF $AF $7F $00 $26 $12 $F6 $09 $06 $2A $EE $11 $CE $B6 $6E $11
; Tile index $05A
.db $7F $CB $D4 $BF $9F $2F $30 $FF $1F $2F $30 $FF $3F $0B $34 $FF $9F $2F $B0 $FF $5F $2F $70 $FF $5F $2F $30 $FF $7F $0F $70 $FF
; Tile index $05B
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FE $FE $01 $FF $F1 $F1 $0E $FF $B6 $B6 $49 $FF $5B $5B $A4 $FF
; Tile index $05C
.db $FB $FB $04 $FF $FA $FA $05 $FF $FA $FA $05 $FF $51 $51 $AE $FF $02 $02 $FD $FF $15 $15 $EA $FF $AA $AA $55 $FF $BD $BD $42 $FF
; Tile index $05D
.db $6A $6A $95 $FF $9A $9A $65 $FF $B7 $B7 $48 $FF $EE $EE $11 $FF $BF $BF $40 $FF $FB $FB $04 $FF $FE $FE $01 $FF $B7 $B7 $48 $FF
; Tile index $05E
.db $BD $BD $42 $FF $EF $EF $10 $FF $36 $36 $C9 $FF $D7 $D7 $28 $FF $EF $EF $10 $FF $B7 $B7 $48 $FF $DF $DF $20 $FF $F5 $F5 $0A $FF
; Tile index $05F
.db $6E $6E $91 $FF $AD $AD $52 $FF $EF $EF $10 $FF $76 $76 $89 $FF $BB $BB $44 $FF $EA $EA $15 $FF $75 $75 $8A $FF $B9 $B9 $46 $FF
; Tile index $060
.db $DA $DA $25 $FF $EE $EE $11 $FF $B5 $B5 $4A $FF $D6 $D6 $29 $FF $35 $35 $CA $FF $AE $AE $51 $FF $41 $41 $BE $FF $15 $15 $EA $FF
; Tile index $061
.db $FF $FF $00 $FF $F7 $FF $08 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FB $FF $04 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $062
.db $FF $FF $00 $FF $DF $FF $20 $FF $FD $FF $02 $FF $7F $FF $80 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $063
.db $FF $FF $00 $FF $B5 $FF $4A $FF $FF $FF $00 $FF $EE $FF $11 $FF $FF $FF $00 $FF $7F $FF $80 $FF $FE $FF $01 $FF $F7 $FF $08 $FF
; Tile index $064
.db $AF $FB $54 $FF $FB $FF $04 $FF $FF $B6 $49 $FF $ED $FF $12 $FF $FF $FB $04 $FF $DA $FF $25 $FF $FF $FD $02 $FF $F7 $FE $09 $FF
; Tile index $065
.db $57 $AB $FD $F9 $67 $91 $F6 $F8 $A7 $D3 $75 $F9 $DF $6A $BC $F0 $A7 $C9 $6F $F9 $D7 $A2 $74 $F8 $E7 $D9 $3E $F8 $B3 $C5 $77 $FD
; Tile index $066
.db $7F $EC $03 $00 $FF $BC $9B $98 $FF $D9 $02 $00 $FF $FE $55 $54 $FF $EF $8B $8B $FF $FB $B1 $B1 $FF $AF $8E $8E $FF $7D $29 $29
; Tile index $067
.db $FF $F8 $A7 $A0 $FE $D9 $77 $50 $FE $69 $B6 $21 $FE $75 $EA $61 $FF $B0 $4F $00 $FE $79 $B6 $31 $FE $8D $72 $01 $FF $AA $D5 $80
; Tile index $068
.db $4C $00 $44 $BF $86 $00 $80 $7F $82 $00 $80 $7F $40 $00 $40 $BF $80 $00 $80 $7F $50 $00 $50 $AF $A0 $00 $A0 $5F $C8 $00 $C8 $37
; Tile index $069
.db $40 $40 $40 $BF $01 $11 $01 $FE $00 $40 $00 $FF $09 $00 $00 $FF $07 $00 $00 $FF $00 $40 $00 $FF $01 $00 $00 $FF $00 $00 $00 $FF
; Tile index $06A
.db $90 $80 $90 $7F $20 $00 $00 $FF $00 $00 $00 $FF $10 $00 $10 $FF $02 $00 $02 $FD $00 $00 $00 $FF $0A $09 $0A $F5 $0F $2E $0F $F0
; Tile index $06B
.db $08 $00 $00 $FF $50 $00 $50 $FF $11 $11 $11 $EE $AE $05 $AF $50 $F0 $FF $FF $00 $A4 $5B $BF $40 $C0 $7D $FF $00 $20 $C6 $7F $80
; Tile index $06C
.db $40 $40 $40 $BF $09 $09 $09 $F6 $F4 $FF $F4 $0B $10 $FE $F8 $07 $88 $FF $F8 $07 $00 $FF $EC $13 $00 $7F $F0 $0F $00 $FF $F4 $0B
; Tile index $06D
.db $01 $A6 $01 $FE $00 $09 $00 $FF $1F $A0 $00 $FF $6E $00 $00 $FF $BF $40 $00 $FF $7F $80 $02 $FF $5F $A0 $00 $FF $5F $A0 $01 $FF
; Tile index $06E
.db $00 $FF $3B $C4 $00 $FF $05 $FA $00 $1F $00 $FF $FE $01 $00 $FF $FF $00 $00 $FF $FF $00 $80 $FF $FF $00 $50 $FF $FF $00 $08 $FF
; Tile index $06F
.db $0E $4E $F1 $00 $00 $D4 $7F $80 $00 $FD $BF $40 $00 $FF $0F $F0 $80 $7F $03 $FC $40 $BF $02 $FD $E0 $1F $00 $FF $E0 $1F $00 $FF
; Tile index $070
.db $81 $92 $7F $00 $44 $1B $FF $00 $00 $4D $F7 $08 $00 $7F $FB $04 $00 $AF $F8 $07 $00 $FF $E9 $16 $00 $FF $58 $A7 $00 $FF $20 $DF
; Tile index $071
.db $28 $74 $F8 $07 $0A $66 $DA $25 $22 $D6 $B2 $4D $00 $F5 $60 $9F $10 $E0 $C0 $3F $00 $F5 $00 $FF $19 $E0 $00 $FF $0F $C0 $00 $FF
; Tile index $072
.db $3F $2F $10 $FF $3F $2F $10 $FF $5B $0B $34 $FF $6F $0F $70 $FF $77 $07 $78 $FF $F7 $03 $BC $FF $F7 $07 $78 $FF $77 $03 $7C $FF
; Tile index $073
.db $BE $BE $41 $FF $FD $FD $02 $FF $FF $FF $00 $FF $ED $ED $12 $FF $FF $FE $01 $FF $FB $EF $14 $FF $FE $55 $AB $FF $FE $FA $05 $FF
; Tile index $074
.db $AB $AB $54 $FF $79 $79 $86 $FF $FE $FE $01 $FF $6B $6B $94 $FF $86 $86 $79 $FF $F1 $B1 $4E $FF $98 $68 $F7 $FF $E6 $BA $5D $FF
; Tile index $075
.db $DC $DC $23 $FF $EB $EB $14 $FF $B6 $B6 $49 $FF $A8 $A8 $57 $FF $52 $52 $AD $FF $D4 $D4 $2B $FF $92 $92 $6D $FF $A9 $A9 $56 $FF
; Tile index $076
.db $B5 $B5 $4A $FF $C2 $C2 $3D $FF $09 $09 $F6 $FF $A4 $A4 $5B $FF $99 $99 $66 $FF $40 $40 $BF $FF $94 $94 $6B $FF $72 $72 $8D $FF
; Tile index $077
.db $68 $68 $97 $FF $00 $00 $FF $FF $40 $40 $BF $FF $00 $00 $FF $FF $08 $08 $F7 $FF $01 $01 $FE $FF $00 $00 $FF $FF $28 $28 $D7 $FF
; Tile index $078
.db $00 $00 $FF $FF $0A $0A $F5 $FF $90 $90 $6F $FF $4A $4A $B5 $FF $90 $90 $6F $FF $05 $05 $FA $FF $54 $54 $AB $FF $2A $2A $D5 $FF
; Tile index $079
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $B7 $FF $48 $FF $FD $FF $02 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $07A
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $B6 $FF $49 $FF $FF $FF $00 $FF $FF $FF $00 $FF $6D $FF $92 $FF $FF $FF $00 $FF
; Tile index $07B
.db $FF $FF $00 $FF $FE $FF $01 $FF $FF $FF $00 $FF $ED $FF $12 $FF $FF $FF $00 $FF $FF $FF $00 $FF $DF $FF $20 $FF $FF $FF $00 $FF
; Tile index $07C
.db $FE $DF $21 $FF $DF $FD $22 $FF $F6 $FF $09 $FF $FD $FF $02 $FF $DF $F7 $28 $FF $77 $FF $88 $FF $FF $FF $00 $FF $DB $FF $24 $FF
; Tile index $07D
.db $E7 $79 $9E $F8 $B3 $D4 $67 $FC $D7 $68 $BF $F8 $F3 $D8 $2B $FC $BB $EC $57 $FC $ED $74 $99 $FE $7D $FE $83 $FE $FE $F5 $0B $FF
; Tile index $07E
.db $FF $B7 $A4 $A4 $FF $DD $5D $5D $FF $AB $23 $23 $FF $E6 $26 $26 $FF $F9 $59 $59 $FF $53 $C3 $43 $FF $F4 $14 $14 $FF $73 $E3 $63
; Tile index $07F
.db $FF $C0 $BF $80 $FF $E8 $57 $40 $FF $A2 $5D $00 $FF $E4 $DB $C0 $FF $FB $C4 $C0 $FF $74 $6B $60 $FF $EC $A3 $A0 $FF $7E $6D $6C
; Tile index $080
.db $F4 $00 $F4 $0B $FD $00 $FD $02 $8B $74 $8B $74 $50 $A8 $D0 $2F $DA $20 $DA $25 $D4 $A8 $54 $2B $E9 $16 $E9 $16 $76 $89 $F6 $09
; Tile index $081
.db $00 $00 $00 $FF $00 $00 $00 $FF $F0 $50 $F0 $0F $1D $19 $1D $E2 $A9 $09 $A9 $56 $1D $18 $1D $E2 $2E $07 $2E $D1 $8F $05 $8F $70
; Tile index $082
.db $9F $9F $9F $60 $3E $3D $3E $C1 $75 $7B $75 $8A $A3 $A6 $A3 $5C $5E $5B $5F $A0 $E9 $DE $FB $04 $F2 $FD $FF $00 $AA $55 $FF $00
; Tile index $083
.db $00 $FD $FF $00 $A0 $5E $FF $00 $10 $E5 $FF $00 $00 $DE $FF $00 $50 $A5 $FF $00 $00 $A5 $FF $00 $48 $12 $FF $00 $90 $44 $FF $00
; Tile index $084
.db $00 $BF $F8 $07 $00 $FF $FA $05 $00 $BF $FC $03 $00 $FF $FE $01 $00 $5F $FD $02 $00 $7F $FF $00 $00 $AF $FF $00 $00 $BF $FF $00
; Tile index $085
.db $2F $C0 $00 $FF $5B $A0 $00 $FF $6F $D0 $40 $BF $2B $D4 $00 $FF $05 $FA $00 $FF $01 $FE $40 $BF $14 $FF $54 $AB $01 $FF $A9 $56
; Tile index $086
.db $FF $00 $24 $FF $FF $00 $40 $FF $FF $00 $04 $FF $FF $00 $00 $FF $FF $00 $00 $FF $5F $A0 $00 $FF $AF $50 $00 $FF $1A $E5 $00 $FF
; Tile index $087
.db $D8 $27 $00 $FF $F5 $0A $00 $FF $FF $00 $00 $FF $FD $02 $00 $FF $FF $00 $00 $FF $FF $00 $80 $FF $FF $00 $00 $FF $DF $20 $00 $FF
; Tile index $088
.db $00 $FF $00 $FF $04 $FA $00 $FF $5A $A5 $00 $FF $CD $32 $00 $FF $F5 $0A $00 $FF $FD $02 $00 $FF $FF $00 $00 $FF $F6 $09 $00 $FF
; Tile index $089
.db $2D $90 $01 $FF $B7 $40 $00 $FF $9F $60 $00 $FF $3F $C0 $02 $FF $1F $E0 $00 $FF $5D $A3 $01 $FE $68 $96 $06 $F9 $B0 $4F $04 $FB
; Tile index $08A
.db $EF $05 $2A $FF $EB $08 $A7 $FF $F7 $23 $2C $DF $B5 $60 $3F $DF $72 $C0 $7F $BF $76 $C2 $7D $BF $93 $80 $BF $7F $C5 $80 $FF $7F
; Tile index $08B
.db $F5 $00 $FF $FF $BF $00 $FF $FF $7F $22 $DD $FF $F7 $08 $FF $FF $E8 $15 $F5 $FF $D2 $3C $FE $EF $ED $12 $F7 $FF $EA $15 $F5 $FF
; Tile index $08C
.db $F9 $57 $AE $FF $58 $06 $FE $FF $BB $11 $EE $FF $D7 $82 $7D $FF $EB $00 $FF $FF $B5 $40 $FF $FF $7D $80 $FF $FF $BB $40 $7F $FF
; Tile index $08D
.db $A6 $A6 $59 $FF $4B $CB $B4 $FF $25 $E5 $DA $FF $9A $FA $65 $FF $4A $BA $F5 $FF $C6 $BE $79 $FF $F3 $8F $7C $FF $B8 $2E $D7 $FF
; Tile index $08E
.db $44 $44 $BB $FF $A9 $A9 $56 $FF $25 $25 $DA $FF $51 $51 $AE $FF $6E $6E $91 $FF $52 $52 $AD $FF $49 $49 $B6 $FF $24 $24 $DB $FF
; Tile index $08F
.db $85 $85 $7A $FF $55 $55 $AA $FF $10 $10 $EF $FF $6F $6F $90 $FF $00 $00 $FF $FF $A0 $A0 $5F $FF $55 $55 $AA $FF $02 $02 $FD $FF
; Tile index $090
.db $02 $02 $FD $FF $69 $69 $96 $FF $58 $58 $A7 $FF $50 $50 $AF $FF $80 $80 $7F $FF $00 $00 $FF $FF $00 $00 $FF $FF $40 $40 $BF $FF
; Tile index $091
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $092
.db $FF $FF $00 $FF $F7 $FF $08 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $093
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $EF $FF $10 $FF $FE $FF $01 $FF $FF $FF $00 $FF $7F $FF $80 $FF
; Tile index $094
.db $FF $FF $00 $FF $FD $FF $02 $FF $FF $FF $00 $FF $F7 $FF $08 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $095
.db $FA $FD $07 $FF $BF $F4 $4B $FF $FF $FF $00 $FF $FF $FD $02 $FF $FF $EF $10 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $EF $10 $FF
; Tile index $096
.db $FF $1C $DC $1C $7F $35 $55 $95 $7F $BB $FB $BB $3F $55 $65 $C5 $BF $4C $FC $CC $9F $4D $D5 $E5 $9F $EE $76 $E6 $CF $52 $9C $F0
; Tile index $097
.db $FF $BF $B8 $B8 $FF $5F $5C $5C $FF $6F $6E $6E $FF $5B $5B $5B $FF $BF $BF $BF $FF $27 $27 $27 $FF $95 $95 $95 $FF $A2 $A2 $A2
; Tile index $098
.db $CD $32 $CD $32 $F2 $8D $72 $0D $FE $A1 $5E $01 $FA $E5 $1A $05 $FF $DC $A3 $80 $FF $A0 $5F $00 $FE $81 $FE $81 $FC $E3 $DC $C3
; Tile index $099
.db $67 $AF $67 $98 $CA $21 $CB $34 $B4 $4F $B4 $4B $AD $53 $AD $52 $53 $AC $57 $A8 $AC $53 $AD $52 $55 $AA $F7 $08 $A9 $56 $BF $40
; Tile index $09A
.db $A8 $F5 $FF $00 $A3 $5C $BF $40 $48 $F3 $FF $00 $AB $56 $FD $00 $24 $D1 $BF $40 $AA $40 $FF $00 $49 $94 $FF $00 $25 $D0 $FF $00
; Tile index $09B
.db $00 $21 $FF $00 $44 $10 $FF $00 $10 $C2 $FF $00 $40 $28 $FF $00 $88 $0B $F7 $00 $28 $82 $FF $00 $A0 $8B $7F $00 $10 $8B $FF $00
; Tile index $09C
.db $00 $2B $FF $00 $00 $9F $FF $00 $00 $2B $FF $00 $00 $EF $FF $00 $00 $BF $FF $00 $00 $FF $FD $02 $00 $7F $F5 $0A $00 $FF $E8 $17
; Tile index $09D
.db $00 $FF $F0 $0F $00 $FF $90 $6F $05 $FF $E5 $1A $00 $FF $48 $B7 $03 $FD $21 $DE $0F $FA $0A $F5 $0B $F4 $00 $FF $1F $E0 $00 $FF
; Tile index $09E
.db $22 $DD $00 $FF $9A $65 $00 $FF $01 $B6 $00 $FF $AA $55 $00 $FF $B7 $48 $00 $FF $7F $80 $00 $FF $FF $00 $00 $FF $FE $03 $03 $FC
; Tile index $09F
.db $82 $7D $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $40 $BF $01 $FE $F0 $0F $03 $FC $C0 $33 $1F $E0 $00 $C3 $7F $80 $00 $50 $FF $00
; Tile index $0A0
.db $BF $40 $00 $FF $5D $A2 $00 $FF $22 $DD $00 $FF $07 $F8 $00 $FF $00 $FF $E0 $1F $01 $FE $50 $AF $00 $5F $F8 $07 $00 $1F $FC $03
; Tile index $0A1
.db $C2 $3D $06 $F8 $E7 $1D $08 $F0 $CF $3E $01 $F0 $CF $38 $1D $E6 $4F $B1 $31 $CE $0C $D0 $20 $DF $00 $FF $1D $E2 $00 $FF $7E $81
; Tile index $0A2
.db $DB $80 $5F $3F $FB $B8 $C7 $BF $3B $00 $3F $FF $97 $40 $9F $7F $5F $80 $0F $FF $1F $D0 $1F $EF $27 $D0 $C4 $3F $3B $C0 $03 $FF
; Tile index $0A3
.db $D5 $3A $FB $EF $CB $1D $DF $F6 $F4 $0B $FB $FF $F9 $1C $FD $E7 $C0 $1B $DB $FF $D2 $2D $ED $FF $F5 $1F $FF $EA $D4 $3F $BF $EB
; Tile index $0A4
.db $4F $98 $DF $F7 $5F $A0 $FF $FF $F7 $08 $BF $FF $2F $D1 $FE $FF $BB $44 $7D $FF $4E $B1 $BF $FF $35 $EB $FA $DF $A6 $54 $F2 $FF
; Tile index $0A5
.db $7D $03 $FE $FF $BC $13 $EF $FF $FE $04 $FA $FF $AE $03 $FD $FF $DB $00 $FF $FF $E6 $00 $FF $FF $BE $40 $7F $FF $FD $80 $7F $FF
; Tile index $0A6
.db $55 $55 $AA $FF $94 $94 $6B $FF $43 $C3 $BC $FF $60 $A0 $DF $FF $B4 $74 $CB $FF $B8 $58 $E7 $FF $A8 $58 $F7 $FF $6C $3C $D3 $FF
; Tile index $0A7
.db $A0 $A0 $5F $FF $48 $48 $B7 $FF $01 $01 $FE $FF $00 $00 $FF $FF $80 $80 $7F $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $0A8
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $0A9
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FD $FF $02 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0AA
.db $FF $FF $00 $FF $F7 $FF $08 $FF $BF $FF $40 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $F7 $FF $08 $FF
; Tile index $0AB
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FD $FD $02 $FF
; Tile index $0AC
.db $FF $FB $04 $FF $FF $FF $00 $FF $7F $7F $80 $FF $DD $DD $22 $FF $F6 $F6 $09 $FF $69 $69 $96 $FF $B6 $B6 $49 $FF $D9 $D9 $26 $FF
; Tile index $0AD
.db $CF $F6 $3A $F2 $EF $93 $7D $F1 $B7 $AB $5F $FB $7B $55 $AF $FD $BB $B4 $4F $FC $5E $5D $A3 $FF $4E $4F $B1 $FF $17 $13 $EC $FF
; Tile index $0AE
.db $FF $8A $8A $8A $FF $A1 $A1 $A1 $FF $D4 $D4 $D4 $FF $82 $83 $82 $FF $E4 $E3 $E0 $FF $F5 $F6 $F4 $7F $93 $D0 $90 $3F $DA $F9 $D8
; Tile index $0AF
.db $FF $4E $41 $40 $FF $7B $68 $68 $FF $2F $08 $08 $FF $3D $C4 $04 $FF $4D $B2 $00 $FB $F5 $0E $00 $E4 $E5 $1B $00 $C1 $D5 $2E $10
; Tile index $0B0
.db $F6 $09 $FF $00 $FB $EC $17 $00 $FE $F6 $09 $00 $FD $7A $05 $02 $FA $F4 $0F $00 $F1 $40 $BF $00 $77 $F5 $0A $80 $89 $A8 $77 $00
; Tile index $0B1
.db $52 $A4 $FF $00 $54 $00 $FF $00 $49 $00 $FF $00 $A6 $03 $FD $00 $48 $20 $FF $00 $95 $C0 $7F $00 $40 $68 $BF $00 $4A $20 $FF $00
; Tile index $0B2
.db $48 $17 $FF $00 $80 $2F $FF $00 $00 $BF $FF $00 $00 $7F $FF $00 $80 $1F $FE $01 $00 $6F $FF $00 $00 $5F $FF $00 $00 $2F $FF $00
; Tile index $0B3
.db $00 $FF $40 $BF $01 $FE $80 $7F $02 $FD $40 $BF $05 $FA $40 $BF $00 $FF $C0 $3F $02 $FF $2B $D4 $00 $FF $6B $94 $00 $FF $97 $68
; Tile index $0B4
.db $7F $80 $00 $FF $FF $00 $00 $FF $F5 $0F $05 $FA $14 $FB $10 $EF $04 $FF $3F $C0 $00 $FC $FF $00 $00 $E3 $FC $00 $00 $A1 $FF $00
; Tile index $0B5
.db $F0 $1D $1F $E0 $E0 $7F $7F $80 $0D $FA $0C $F0 $47 $F8 $70 $80 $1E $67 $C0 $01 $5B $B4 $0D $03 $06 $FB $1E $01 $18 $FA $F8 $07
; Tile index $0B6
.db $F1 $3F $C0 $00 $BD $C3 $80 $80 $FE $02 $01 $00 $FC $04 $03 $00 $60 $B4 $EB $A4 $30 $0B $37 $C8 $00 $FF $DF $20 $00 $77 $0C $F3
; Tile index $0B7
.db $80 $8F $7C $03 $00 $8F $78 $07 $00 $0F $FC $03 $00 $1F $F8 $07 $01 $9E $F8 $07 $03 $FC $D0 $2F $03 $FC $00 $FF $07 $F8 $00 $FF
; Tile index $0B8
.db $43 $BC $00 $FF $3F $C0 $01 $FF $FF $00 $00 $FF $FF $00 $02 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FC $03 $00 $FF $F8 $07 $47 $F8
; Tile index $0B9
.db $FF $00 $08 $FF $FF $00 $52 $FF $FF $00 $80 $FF $FF $00 $20 $FF $FF $01 $01 $FE $FF $0A $0A $F5 $07 $FF $07 $F8 $00 $FF $FE $01
; Tile index $0BA
.db $D1 $3F $BF $EE $CC $17 $DF $F3 $B2 $7F $FF $CD $CC $17 $5F $F3 $5A $25 $3F $E5 $3E $71 $7F $C1 $29 $96 $BF $D6 $FE $41 $7F $81
; Tile index $0BB
.db $13 $BC $BF $EF $0D $F6 $FF $FB $B2 $DF $DF $6D $0B $BD $BF $F6 $AC $DB $DF $77 $4B $F4 $FD $BF $02 $D7 $D7 $FD $89 $E6 $EE $7F
; Tile index $0BC
.db $75 $80 $FF $FF $FA $20 $DF $FF $F9 $00 $FF $FF $2E $D0 $FF $FF $1B $40 $5B $FF $7F $84 $FB $FF $FB $04 $FF $FF $7D $92 $EF $FF
; Tile index $0BD
.db $74 $0C $FB $FF $64 $18 $FF $FF $FA $26 $DD $FF $38 $0C $F7 $FF $DB $05 $FE $FF $EC $02 $FF $FF $BF $0A $F5 $FF $D5 $02 $FF $FF
; Tile index $0BE
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $80 $7F $FF $80 $80 $7F $FF
; Tile index $0BF
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $7F $7F $80 $FF $FF $FF $00 $FF $7F $7F $80 $FF $FF $FF $00 $FF $7F $7F $80 $FF
; Tile index $0C0
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FE $FE $01 $FF
; Tile index $0C1
.db $FF $FF $00 $FF $F5 $F5 $0A $FF $FA $FA $05 $FF $F7 $F7 $08 $FF $D4 $D4 $2B $FF $AA $AA $55 $FF $52 $52 $AD $FF $95 $95 $6A $FF
; Tile index $0C2
.db $2A $2A $D5 $FF $F5 $F5 $0A $FF $EA $EA $15 $FF $F4 $F4 $0B $FF $91 $91 $6E $FF $D2 $D2 $2D $FF $A0 $A0 $5F $FF $54 $54 $AB $FF
; Tile index $0C3
.db $A3 $A3 $5C $FF $22 $22 $DD $FF $08 $08 $F7 $FF $20 $20 $DF $FF $00 $00 $FF $FF $48 $40 $BF $FF $20 $00 $FF $FF $23 $21 $DE $FF
; Tile index $0C4
.db $9F $EC $7D $EC $CF $F5 $38 $F0 $37 $19 $EE $F8 $1D $00 $FD $FE $BC $10 $EC $FF $FF $10 $EF $FF $FF $00 $FE $FF $FD $00 $FD $FF
; Tile index $0C5
.db $C1 $E9 $36 $08 $2E $BE $D1 $00 $C4 $84 $7B $00 $C4 $94 $7B $00 $E1 $31 $DE $00 $90 $76 $0B $E4 $80 $31 $0F $F0 $E0 $1C $03 $FC
; Tile index $0C6
.db $E4 $F0 $1F $00 $05 $A5 $5A $A0 $3E $3F $C1 $00 $3E $3E $C1 $00 $10 $1D $E3 $00 $00 $0C $F3 $00 $03 $D7 $28 $D0 $41 $59 $A6 $18
; Tile index $0C7
.db $08 $08 $F7 $00 $A5 $05 $FA $00 $12 $12 $ED $00 $05 $45 $FA $00 $55 $55 $AA $00 $0D $0D $F2 $00 $3F $3F $C0 $00 $3F $3F $C0 $00
; Tile index $0C8
.db $00 $0B $FF $00 $20 $07 $FF $00 $00 $0A $FF $00 $80 $82 $7F $00 $60 $60 $9F $00 $A8 $A8 $57 $00 $F0 $F0 $0F $00 $58 $58 $A7 $00
; Tile index $0C9
.db $00 $FF $D5 $2A $00 $FF $FA $05 $00 $FF $FD $02 $00 $FF $FF $00 $00 $AF $FF $00 $00 $5A $FF $00 $00 $2A $FF $00 $00 $15 $FF $00
; Tile index $0CA
.db $02 $FD $7C $83 $15 $EA $00 $FF $00 $FF $A2 $5D $00 $FF $FD $02 $00 $FF $FF $00 $00 $FF $FF $00 $00 $AF $FF $00 $00 $2F $FF $00
; Tile index $0CB
.db $FF $00 $00 $FF $BE $41 $00 $FF $15 $EA $00 $FF $05 $FA $80 $7F $03 $FC $40 $BF $0F $F0 $80 $7F $33 $FC $F0 $0F $57 $F8 $50 $AF
; Tile index $0CC
.db $01 $FE $30 $CF $0F $F0 $00 $FF $7F $80 $00 $FF $FF $00 $14 $FF $FF $00 $16 $FF $FF $00 $68 $FF $FF $00 $10 $FF $FF $00 $10 $FF
; Tile index $0CD
.db $07 $F8 $00 $FF $FF $00 $00 $FF $C3 $3C $00 $FF $C7 $38 $00 $FF $00 $FF $08 $F7 $80 $4F $7C $83 $00 $DF $70 $8F $06 $99 $78 $87
; Tile index $0CE
.db $F8 $04 $23 $FC $FC $03 $50 $FF $FC $03 $20 $FF $FC $03 $00 $FF $F0 $0F $03 $FC $00 $FC $0F $F0 $00 $C1 $7E $81 $01 $02 $FC $03
; Tile index $0CF
.db $00 $1F $FF $00 $01 $0B $FF $00 $01 $83 $FF $00 $03 $22 $DE $01 $0B $1D $ED $0A $07 $A7 $DF $00 $0D $8E $7F $82 $0F $CB $3B $C4
; Tile index $0D0
.db $12 $6D $7F $ED $6D $52 $7F $92 $30 $CF $FF $CF $FA $85 $FF $05 $E9 $16 $FF $16 $5D $A2 $FF $A2 $B6 $49 $FF $49 $02 $BD $BF $FD
; Tile index $0D1
.db $24 $F9 $FD $DF $43 $EB $E9 $BE $89 $D6 $DF $7F $20 $F5 $F5 $DF $51 $BA $FB $AF $AA $77 $FF $55 $54 $BF $FF $AB $95 $FF $FF $6A
; Tile index $0D2
.db $FF $00 $FF $FF $7D $8A $F7 $FF $17 $A8 $BF $FF $85 $52 $D7 $FF $B3 $0C $AF $FF $9D $62 $FB $FF $CD $82 $8F $7F $0C $D1 $DD $FF
; Tile index $0D3
.db $DA $01 $FF $FF $AD $40 $FF $FF $F3 $02 $FD $FF $FF $80 $7F $FF $E9 $00 $FF $FF $F6 $00 $FF $FF $BD $00 $FF $FF $FD $00 $FF $FF
; Tile index $0D4
.db $80 $80 $7F $FF $C0 $C0 $3F $FF $00 $80 $FF $FF $C0 $80 $7F $FF $40 $80 $FF $FF $E0 $60 $9F $FF $E0 $80 $7F $FF $E0 $20 $DF $FF
; Tile index $0D5
.db $FF $FF $00 $FF $7F $7F $80 $FF $FF $FF $00 $FF $7F $7F $80 $FF $BF $BF $40 $FF $6F $6F $90 $FF $7F $7F $80 $FF $56 $56 $A9 $FF
; Tile index $0D6
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $B4 $B4 $4B $FF
; Tile index $0D7
.db $FD $FD $02 $FF $F5 $F5 $0A $FF $FA $FA $05 $FF $CA $CA $35 $FF $B5 $B5 $4A $FF $D4 $D4 $2B $FF $55 $55 $AA $FF $AA $AA $55 $FF
; Tile index $0D8
.db $54 $54 $AB $FF $52 $52 $AD $FF $55 $55 $AA $FF $92 $92 $6D $FF $28 $28 $D7 $FF $85 $85 $7A $FF $50 $50 $AF $FF $0A $0A $F5 $FF
; Tile index $0D9
.db $00 $00 $FF $FF $A0 $A0 $5F $FF $00 $00 $FF $FF $40 $40 $BF $FF $08 $08 $F7 $FF $10 $10 $EF $FF $80 $80 $7F $FF $44 $44 $BB $FF
; Tile index $0DA
.db $0F $00 $FF $FF $0F $00 $FF $FF $0F $00 $FE $FF $0A $00 $FA $FF $05 $00 $F5 $FF $3A $04 $FC $FF $15 $00 $F0 $FF $32 $04 $F4 $FF
; Tile index $0DB
.db $FF $00 $F4 $FF $FF $00 $50 $FF $FE $00 $A4 $FF $F9 $00 $90 $FF $DA $01 $00 $FF $E4 $02 $40 $FF $50 $0B $00 $FF $E0 $06 $00 $FF
; Tile index $0DC
.db $E0 $1F $00 $FF $40 $1F $01 $FE $A0 $4F $00 $FF $00 $3F $01 $FE $00 $7F $01 $FE $00 $FF $06 $F9 $00 $FF $15 $EA $50 $FF $58 $A7
; Tile index $0DD
.db $00 $46 $FB $04 $00 $AA $D7 $28 $00 $87 $7E $81 $00 $E0 $1F $E0 $00 $FC $C7 $38 $00 $FE $17 $E8 $00 $FF $09 $F6 $00 $FF $07 $F8
; Tile index $0DE
.db $17 $1F $E0 $00 $0D $8F $F0 $00 $02 $CE $B1 $40 $11 $1F $E0 $00 $7C $7F $80 $00 $05 $07 $F8 $00 $07 $B7 $F8 $00 $01 $21 $FE $00
; Tile index $0DF
.db $F4 $F4 $0B $00 $9A $DA $25 $00 $98 $BA $45 $00 $F9 $F9 $06 $00 $78 $FD $02 $00 $7E $FE $01 $00 $80 $F5 $0A $00 $D3 $DB $24 $00
; Tile index $0E0
.db $00 $02 $FF $00 $00 $02 $FF $00 $00 $00 $FF $00 $80 $80 $7F $00 $40 $40 $BF $00 $40 $40 $BF $00 $C0 $D0 $2F $00 $44 $44 $BB $00
; Tile index $0E1
.db $00 $DF $FE $01 $00 $AF $FF $00 $00 $43 $FF $00 $00 $15 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00
; Tile index $0E2
.db $5B $EC $E8 $17 $7F $FA $FA $05 $00 $FF $F4 $0B $00 $FF $FD $02 $00 $BF $FF $00 $00 $15 $FF $00 $00 $41 $FF $00 $00 $08 $FF $00
; Tile index $0E3
.db $FC $03 $00 $FF $F8 $07 $00 $FF $00 $FF $0B $F4 $00 $FF $3F $C0 $00 $FC $FF $00 $00 $E8 $FF $00 $00 $01 $FE $00 $00 $03 $FC $00
; Tile index $0E4
.db $01 $CD $FA $04 $00 $C0 $FF $00 $00 $83 $FF $00 $00 $06 $FF $00 $00 $01 $FF $00 $00 $85 $7F $00 $00 $C0 $3F $00 $00 $01 $FE $00
; Tile index $0E5
.db $87 $98 $70 $0F $12 $ED $80 $7F $00 $FF $03 $FC $00 $F0 $7F $80 $04 $67 $FB $00 $01 $1E $E4 $03 $0F $E0 $10 $0F $1F $A0 $60 $1F
; Tile index $0E6
.db $4F $D0 $30 $8F $07 $38 $F0 $0F $0F $74 $C4 $3B $3F $C0 $80 $7F $7F $80 $00 $FF $FF $00 $02 $FF $FF $00 $1B $FF $FF $00 $FE $FF
; Tile index $0E7
.db $FF $00 $A3 $FF $FF $00 $5D $FF $FF $00 $22 $FF $FF $00 $2A $FF $FF $00 $D5 $FF $FF $00 $7A $FF $FF $00 $EF $FF $FF $00 $FA $FF
; Tile index $0E8
.db $97 $1B $9F $E8 $FC $02 $FE $FF $FF $00 $2A $FF $FF $00 $C5 $FF $FF $00 $A8 $FF $FF $00 $52 $FF $FF $00 $A0 $FF $FF $00 $90 $FF
; Tile index $0E9
.db $46 $A9 $AF $FF $1F $B0 $BF $EF $AF $70 $FF $DF $F7 $18 $5F $EF $E7 $00 $E3 $FF $F2 $05 $57 $FF $F7 $01 $01 $FE $EF $0A $09 $F7
; Tile index $0EA
.db $F7 $00 $FF $FF $9F $40 $FF $FF $D9 $00 $FF $FF $7A $90 $EF $FF $D6 $00 $FF $FF $6A $40 $3F $FF $EE $00 $FF $FF $37 $A0 $9F $FF
; Tile index $0EB
.db $70 $40 $BF $FF $B0 $50 $EF $FF $D0 $20 $FF $FF $70 $20 $DF $FF $B8 $00 $FF $FF $B8 $18 $E7 $FF $AC $10 $FF $FF $50 $08 $FF $FF
; Tile index $0EC
.db $BD $BD $42 $FF $4A $4A $B5 $FF $5A $5A $A5 $FF $25 $25 $DA $FF $AA $AA $55 $FF $26 $26 $D9 $FF $55 $55 $AA $FF $29 $29 $D6 $FF
; Tile index $0ED
.db $53 $53 $AC $FF $95 $95 $6A $FF $AA $AA $55 $FF $55 $55 $AA $FF $AA $AA $55 $FF $A9 $A9 $56 $FF $24 $24 $DB $FF $49 $49 $B6 $FF
; Tile index $0EE
.db $54 $54 $AB $FF $FA $FA $05 $FF $25 $25 $DA $FF $A8 $A8 $57 $FF $5B $5B $A4 $FF $54 $54 $AB $FF $91 $91 $6E $FF $4C $4C $B3 $FF
; Tile index $0EF
.db $A0 $A0 $5F $FF $10 $10 $EF $FF $4A $4A $B5 $FF $92 $92 $6D $FF $29 $29 $D6 $FF $D2 $D2 $2D $FF $00 $00 $FF $FF $54 $54 $AB $FF
; Tile index $0F0
.db $20 $20 $DF $FF $94 $94 $6B $FF $00 $00 $FF $FF $40 $40 $BF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $0F1
.db $32 $00 $F0 $FF $31 $00 $F0 $FF $22 $11 $F0 $FF $33 $02 $F2 $FD $11 $03 $F1 $FE $39 $00 $F0 $FF $07 $02 $F2 $FD $33 $02 $F2 $FD
; Tile index $0F2
.db $AA $5F $0A $F5 $42 $BF $02 $FD $98 $3F $18 $E7 $66 $FF $66 $99 $98 $7F $18 $E7 $45 $BE $04 $FB $F5 $5B $51 $AE $7F $AA $2A $D5
; Tile index $0F3
.db $82 $FF $A2 $5D $50 $FE $D0 $2F $0A $FD $08 $F7 $2B $F4 $20 $DF $95 $E0 $80 $7F $57 $A8 $00 $FF $FF $40 $40 $BF $7F $80 $00 $FF
; Tile index $0F4
.db $00 $BF $01 $FE $00 $5F $01 $FE $20 $07 $00 $FF $DC $23 $00 $FF $7A $85 $00 $FF $FE $00 $00 $FF $FF $00 $00 $FF $FB $00 $88 $FF
; Tile index $0F5
.db $02 $DA $7D $80 $00 $A8 $FF $00 $00 $E4 $7F $80 $00 $EA $7F $80 $00 $F0 $1F $E0 $00 $FA $3F $C0 $00 $FD $07 $F8 $C0 $3D $0F $F0
; Tile index $0F6
.db $FF $FF $00 $00 $EF $EF $10 $00 $7F $7F $80 $00 $BE $BF $40 $00 $6F $6F $90 $00 $3D $3D $C2 $00 $0B $0B $F4 $00 $15 $15 $EA $00
; Tile index $0F7
.db $10 $50 $AF $00 $B4 $B4 $4B $00 $60 $69 $96 $00 $34 $F4 $0B $00 $06 $7E $81 $00 $E1 $FF $00 $00 $42 $47 $B8 $00 $77 $77 $88 $00
; Tile index $0F8
.db $00 $00 $FF $00 $00 $00 $FF $00 $20 $20 $DF $00 $40 $40 $BF $00 $10 $90 $6F $00 $50 $50 $AF $00 $4A $EA $15 $00 $83 $FF $00 $00
; Tile index $0F9
.db $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $A8 $FF $00 $00 $00 $FF $00 $AA $AA $55 $00
; Tile index $0FA
.db $00 $0A $F5 $00 $00 $00 $FF $00 $00 $10 $EF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $07 $F8 $00 $00 $0D $F2 $01 $01 $BA $44 $03
; Tile index $0FB
.db $00 $46 $B9 $00 $00 $39 $C6 $01 $07 $08 $F8 $07 $07 $D8 $30 $0F $3F $40 $C1 $3F $3F $C0 $87 $7F $FF $00 $0D $FF $FF $00 $17 $FF
; Tile index $0FC
.db $7F $80 $03 $FF $FF $00 $1F $FF $FF $00 $7F $FF $FF $00 $DF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $7F $FF $FF $00 $FE $FF
; Tile index $0FD
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FD $FF $FF $00 $F5 $FF $FF $00 $D0 $FF $FF $00 $C0 $FF
; Tile index $0FE
.db $FF $00 $FD $FF $FF $00 $D4 $FF $FF $00 $A0 $FF $FF $00 $40 $FF $FC $03 $00 $FF $F8 $07 $00 $FF $E0 $1E $01 $FE $C0 $3C $07 $F8
; Tile index $0FF
.db $FF $00 $00 $FF $F7 $0A $02 $FD $80 $7F $00 $FF $01 $FE $10 $EF $00 $FF $B0 $4F $00 $FF $E8 $17 $00 $BF $FE $01 $00 $BF $FF $00
; Tile index $100
.db $F5 $24 $24 $DB $FF $0C $0F $F3 $3F $EC $2C $D3 $4F $BC $1D $E3 $17 $FC $1D $E3 $03 $FC $3F $C3 $0F $E4 $FD $03 $07 $B8 $DB $07
; Tile index $101
.db $D5 $22 $BF $FF $D7 $28 $FF $FF $FF $02 $FD $FF $E9 $10 $FF $FF $E2 $20 $CF $FF $EC $00 $FF $FF $5C $00 $FF $FF $BA $04 $FF $FF
; Tile index $102
.db $BC $10 $EF $FF $5C $8C $F3 $FF $EC $00 $FF $FF $7C $08 $F7 $FF $FC $28 $D7 $FF $9C $08 $F7 $FF $DC $08 $F7 $FF $88 $00 $FF $FF
; Tile index $103
.db $56 $56 $A9 $FF $55 $55 $AA $FF $08 $08 $F7 $FF $46 $46 $B9 $FF $31 $31 $CE $FF $48 $48 $B7 $FF $11 $11 $EE $FF $00 $00 $FF $FF
; Tile index $104
.db $D1 $D1 $2E $FF $5A $5A $A5 $FF $88 $88 $77 $FF $A2 $A2 $5D $FF $49 $49 $B6 $FF $20 $20 $DF $FF $42 $42 $BD $FF $14 $14 $EB $FF
; Tile index $105
.db $29 $29 $D6 $FF $92 $92 $6D $FF $25 $25 $DA $FF $40 $40 $BF $FF $20 $20 $DF $FF $80 $80 $7F $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $106
.db $00 $00 $FF $FF $A0 $A0 $5F $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $40 $40 $BF $FF
; Tile index $107
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $00 $FF $FF $07 $00 $FF $FF $07 $00 $FF $FF
; Tile index $108
.db $BF $05 $F5 $FA $34 $0F $D4 $FB $BE $03 $C3 $FC $6C $17 $D5 $FA $DE $03 $C3 $FC $ED $23 $E1 $DE $8A $0D $89 $F6 $E8 $0F $49 $F6
; Tile index $109
.db $55 $AA $80 $7F $47 $BA $82 $7D $3D $62 $A0 $5F $2F $50 $C0 $3F $9F $E4 $44 $3B $3F $A0 $E0 $1F $0F $B0 $E0 $1F $1F $A0 $E0 $1F
; Tile index $10A
.db $FF $80 $85 $7F $FF $00 $0A $FF $FF $00 $01 $FF $FF $00 $2D $FF $FF $00 $15 $FF $FF $00 $4A $FF $FF $00 $52 $FF $FF $00 $AA $FF
; Tile index $10B
.db $FF $00 $20 $FF $FF $00 $48 $FF $FF $00 $22 $FF $FF $00 $48 $FF $FF $00 $24 $FF $FF $00 $91 $FF $FF $00 $24 $FF $FF $00 $92 $FF
; Tile index $10C
.db $C0 $3F $03 $FC $C0 $1F $03 $FC $F0 $0F $00 $FF $F0 $0B $00 $FF $FC $03 $80 $FF $F8 $07 $00 $FF $F6 $01 $00 $FF $FA $05 $00 $FF
; Tile index $10D
.db $0A $8A $F5 $00 $01 $A1 $FE $00 $00 $D0 $BF $40 $00 $F4 $FF $00 $00 $FF $3F $C0 $00 $FE $2F $D0 $00 $FF $2F $D0 $00 $FF $1F $E0
; Tile index $10E
.db $8B $8B $74 $00 $52 $52 $AD $00 $09 $09 $F6 $00 $00 $00 $FF $00 $00 $80 $FF $00 $00 $A8 $FF $00 $00 $A0 $FF $00 $00 $42 $FF $00
; Tile index $10F
.db $40 $FF $00 $00 $E3 $FC $00 $00 $70 $7F $80 $00 $8F $BC $43 $00 $63 $6F $9C $00 $8A $AB $74 $00 $06 $0E $F9 $00 $14 $B5 $EA $00
; Tile index $110
.db $80 $7F $00 $00 $84 $7F $04 $04 $F1 $FE $F0 $F0 $8E $F1 $00 $00 $02 $FF $01 $00 $CB $FC $4C $4B $8F $FC $1C $03 $BF $E0 $60 $1F
; Tile index $111
.db $07 $F8 $08 $07 $6F $B0 $10 $0F $BF $20 $60 $1F $3F $C0 $C1 $3F $FF $00 $02 $FF $FF $80 $8B $7F $FF $00 $26 $FF $FF $00 $5B $FF
; Tile index $112
.db $FF $00 $5F $FF $FF $00 $37 $FF $FF $00 $DF $FF $FF $00 $6D $FF $FF $00 $BB $FF $FF $00 $BC $FF $FF $00 $D2 $FF $FF $00 $E8 $FF
; Tile index $113
.db $FF $00 $D5 $FF $FF $00 $F4 $FF $FF $00 $48 $FF $FF $00 $A0 $FF $FE $01 $00 $FF $F8 $07 $80 $FF $E0 $1F $01 $FE $C0 $3F $03 $FC
; Tile index $114
.db $FF $00 $00 $FF $FE $01 $00 $FF $F8 $07 $00 $FF $A0 $5F $01 $FE $00 $FF $07 $F8 $00 $E8 $3F $C0 $01 $E9 $FE $00 $02 $92 $FD $00
; Tile index $115
.db $00 $FC $0F $F0 $00 $E8 $1F $E0 $00 $D1 $7E $81 $08 $A8 $F7 $00 $20 $B1 $CF $00 $00 $70 $8F $00 $A0 $BE $41 $00 $02 $FB $0C $F0
; Tile index $116
.db $00 $7F $FF $00 $00 $BF $5F $A0 $00 $7F $D4 $2B $00 $FF $F1 $0E $00 $5F $FC $03 $00 $37 $FA $05 $00 $0B $FE $01 $60 $E0 $1F $00
; Tile index $117
.db $5F $F0 $BB $0F $3B $40 $CB $3F $7F $C4 $CF $3B $3B $C2 $09 $FF $3F $F0 $3D $CF $7F $80 $07 $FF $1F $E0 $87 $7F $1F $20 $C3 $3F
; Tile index $118
.db $7F $00 $FF $FF $BB $00 $FF $FF $5B $21 $FE $FF $F9 $20 $FF $DF $94 $60 $FF $FF $FA $00 $BF $FF $D8 $20 $FF $FF $FC $08 $D7 $FF
; Tile index $119
.db $A4 $00 $FF $FF $D6 $00 $FF $FF $C8 $00 $FF $FF $A2 $00 $FF $FF $C8 $00 $FF $FF $A2 $00 $FF $FF $E0 $00 $FF $FF $D0 $00 $FF $FF
; Tile index $11A
.db $00 $00 $FF $FF $00 $00 $FF $FF $05 $05 $FA $FF $08 $08 $F7 $FF $01 $01 $FE $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $11B
.db $40 $40 $BF $FF $00 $00 $FF $FF $03 $03 $FC $FF $68 $68 $97 $FF $04 $04 $FB $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $11C
.db $5E $5E $A1 $FF $A0 $A0 $5F $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $11D
.db $0E $00 $FC $FF $09 $00 $F9 $FF $09 $04 $FC $FF $19 $00 $F0 $FF $05 $04 $F4 $FB $10 $00 $F0 $FF $33 $02 $F2 $FD $3C $0D $FC $F3
; Tile index $11E
.db $F4 $0F $86 $F9 $78 $07 $07 $F8 $F8 $06 $03 $FC $E0 $1F $03 $FC $60 $1E $0F $F0 $B0 $7C $3F $C0 $00 $F8 $1F $E0 $C0 $F0 $FF $00
; Tile index $11F
.db $0F $B0 $F0 $0F $0F $90 $F0 $0F $2F $38 $D8 $07 $C7 $F8 $08 $07 $07 $B8 $C8 $07 $07 $1C $E4 $03 $63 $7C $84 $03 $03 $FE $06 $01
; Tile index $120
.db $FF $00 $15 $FF $FF $00 $AA $FF $FF $00 $00 $FF $FF $00 $AA $FF $FF $00 $01 $FF $FF $00 $12 $FF $FF $00 $08 $FF $FF $00 $01 $FF
; Tile index $121
.db $FF $00 $48 $FF $FF $00 $22 $FF $FF $00 $80 $FF $FF $00 $20 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $05 $05 $FA $FF $03 $03 $FC
; Tile index $122
.db $F7 $01 $81 $FE $F2 $0B $02 $FD $F8 $17 $10 $EF $DD $2F $0D $F2 $50 $BF $13 $EC $E8 $BF $AF $50 $C0 $7F $57 $A8 $50 $FF $7F $80
; Tile index $123
.db $00 $FF $2F $D0 $80 $FD $DF $20 $00 $FE $7F $80 $00 $F5 $FF $00 $00 $ED $FF $00 $00 $D0 $FF $00 $00 $A8 $FF $00 $00 $40 $FF $00
; Tile index $124
.db $00 $6A $FF $00 $00 $9A $FF $00 $00 $40 $FF $00 $00 $4A $FF $00 $01 $11 $FE $00 $00 $03 $FF $00 $03 $46 $FE $01 $0B $0C $F8 $07
; Tile index $125
.db $0A $8B $F5 $00 $11 $33 $EF $00 $27 $BC $DC $03 $0F $30 $F0 $0F $7F $C0 $C0 $3F $BF $40 $01 $FF $FF $00 $02 $FF $FF $00 $15 $FF
; Tile index $126
.db $7F $C0 $C1 $3F $FF $00 $00 $FF $FF $00 $05 $FF $FF $00 $15 $FF $FF $00 $4B $FF $FF $00 $3A $FF $FF $00 $57 $FF $FF $00 $ED $FF
; Tile index $127
.db $FF $00 $16 $FF $FF $00 $AD $FF $FF $00 $5B $FF $FF $00 $AC $FF $FF $00 $69 $FF $FF $00 $D4 $FF $FF $00 $A0 $FF $FF $00 $48 $FF
; Tile index $128
.db $FF $00 $A0 $FF $FE $01 $90 $FF $FC $03 $40 $FF $F8 $07 $00 $FF $E0 $1F $00 $FF $E0 $1F $03 $FC $C0 $3F $01 $FE $00 $FD $0E $F1
; Tile index $129
.db $00 $FE $0F $F0 $00 $FA $3F $C0 $00 $F4 $2F $D0 $00 $D2 $FF $00 $00 $A8 $5F $A0 $00 $40 $BF $40 $01 $C1 $FE $00 $00 $01 $FE $00
; Tile index $12A
.db $00 $85 $FB $00 $00 $89 $F7 $00 $00 $13 $EF $00 $00 $21 $DF $00 $30 $73 $8F $00 $00 $41 $BF $00 $10 $B1 $4F $00 $00 $A0 $5F $00
; Tile index $12B
.db $1E $E1 $80 $7F $2B $D4 $00 $FF $0B $F4 $80 $7F $16 $EA $82 $7D $05 $FD $E5 $1A $0A $FE $DA $25 $0F $FE $FE $01 $06 $FC $FD $03
; Tile index $12C
.db $1E $DE $E1 $00 $FB $05 $06 $F8 $50 $65 $75 $BF $11 $00 $11 $FF $C0 $3F $FF $FF $EA $13 $FB $FD $A4 $5E $FA $FF $D4 $2B $FF $FF
; Tile index $12D
.db $0F $78 $F8 $07 $2F $18 $FE $07 $FE $E1 $ED $1F $DD $02 $5A $FF $A5 $12 $B7 $FF $4D $40 $0D $FF $6B $94 $FF $FF $27 $48 $6F $FF
; Tile index $12E
.db $F4 $00 $FF $FF $EF $10 $FF $FF $FA $00 $BF $FF $DD $20 $FF $FF $EC $00 $FF $FF $ED $00 $FF $FF $F6 $00 $FF $FF $FD $00 $FF $FF
; Tile index $12F
.db $E8 $00 $FF $FF $E2 $80 $7F $FF $F0 $40 $BF $FF $B4 $00 $FF $FF $94 $00 $FF $FF $84 $00 $FF $FF $84 $00 $FF $FF $A4 $00 $FF $FF
; Tile index $130
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $08 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $131
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $02 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $132
.db $00 $00 $FF $FF $80 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $133
.db $28 $0B $E8 $F7 $33 $05 $E1 $FE $24 $0B $C0 $FF $28 $0F $C8 $F7 $5A $1D $D8 $E7 $7C $3B $F9 $C6 $F8 $37 $B3 $CC $F8 $27 $E7 $D8
; Tile index $134
.db $B8 $C7 $81 $7E $47 $B8 $00 $FF $03 $FC $74 $8B $00 $CF $FF $00 $08 $C9 $F7 $00 $00 $EE $F1 $00 $00 $C7 $F8 $00 $01 $C2 $FC $00
; Tile index $135
.db $08 $D7 $E0 $03 $F8 $0F $02 $F1 $E9 $1F $09 $F0 $40 $BF $1D $E0 $01 $F7 $BC $40 $00 $6F $FF $00 $86 $F9 $51 $2E $00 $DF $39 $06
; Tile index $136
.db $FF $00 $00 $FF $FF $00 $00 $FF $FF $D5 $D5 $2A $7F $A2 $22 $DD $FF $DD $DD $22 $5F $EA $CA $35 $0A $FF $DB $24 $02 $BF $F6 $09
; Tile index $137
.db $F8 $0F $08 $F7 $FC $57 $55 $AA $F4 $5F $55 $AA $FD $AF $AF $50 $F2 $7F $7B $84 $D0 $FF $D7 $28 $00 $FF $5F $A0 $00 $FE $FF $00
; Tile index $138
.db $00 $FE $BF $40 $00 $FD $7F $80 $80 $F6 $FF $00 $00 $F9 $FF $00 $00 $E0 $FF $00 $00 $D0 $FF $00 $03 $C2 $FD $00 $03 $83 $FC $00
; Tile index $139
.db $00 $A0 $FF $00 $01 $81 $FE $00 $04 $24 $FB $00 $24 $26 $DA $01 $59 $5C $A4 $03 $AB $A8 $58 $07 $FF $D0 $3B $0F $BF $E0 $6F $1F
; Tile index $13A
.db $2F $10 $E0 $1F $1F $60 $C2 $3F $7F $80 $15 $FF $FF $00 $0A $FF $FF $00 $AF $FF $FF $00 $B5 $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $13B
.db $FF $00 $25 $FF $FF $00 $9D $FF $FF $00 $B7 $FF $FF $00 $5A $FF $FF $00 $FF $FF $FF $00 $4B $FF $D4 $28 $FC $FF $50 $AE $FE $FF
; Tile index $13C
.db $FF $00 $BB $FF $FF $00 $6A $FF $FF $00 $D4 $FF $FF $00 $A1 $FF $FF $00 $D4 $FF $FF $00 $68 $FF $FF $00 $AA $FF $0F $80 $8F $FF
; Tile index $13D
.db $FE $01 $00 $FF $F9 $06 $00 $FF $F4 $0B $00 $FF $F4 $0B $00 $FF $F0 $0F $00 $FF $A8 $57 $01 $FE $E0 $1F $02 $FD $E0 $1E $03 $FC
; Tile index $13E
.db $00 $FE $15 $EA $00 $F8 $0F $F0 $00 $FE $3D $C2 $00 $F0 $7F $80 $00 $E8 $F7 $08 $00 $A0 $FF $00 $00 $60 $FF $00 $00 $81 $7F $80
; Tile index $13F
.db $00 $83 $FC $00 $01 $07 $F8 $00 $08 $0D $F2 $00 $00 $0A $F5 $00 $04 $15 $EA $00 $08 $0C $F3 $00 $28 $29 $D6 $00 $20 $2A $D5 $00
; Tile index $140
.db $00 $42 $BF $00 $00 $80 $7F $00 $80 $A0 $5F $00 $40 $40 $BF $00 $1F $5F $A0 $00 $00 $A8 $57 $00 $00 $51 $AF $00 $00 $A0 $5F $00
; Tile index $141
.db $0E $78 $FB $07 $0D $38 $FF $07 $18 $70 $F7 $0F $38 $30 $FF $0F $30 $F0 $FF $0F $38 $E0 $FF $1F $70 $E0 $FF $1F $40 $C0 $DF $3F
; Tile index $142
.db $1A $14 $EE $FF $05 $02 $FF $FF $00 $01 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $143
.db $76 $81 $F7 $FF $37 $A8 $9D $FF $BB $44 $FF $FF $FF $10 $EB $FF $7F $24 $DB $FF $3F $00 $FF $FF $3F $34 $CB $FF $06 $00 $FF $FF
; Tile index $144
.db $BD $00 $FF $FF $ED $00 $FF $FF $FD $00 $FF $FF $FB $00 $FF $FF $FD $00 $FF $FF $FB $00 $FF $FF $FB $00 $FF $FF $FF $00 $FF $FF
; Tile index $145
.db $80 $00 $FF $FF $C0 $00 $FF $FF $C8 $00 $FF $FF $10 $00 $FF $FF $C0 $00 $FF $FF $A8 $00 $FF $FF $C0 $00 $FF $FF $00 $00 $FF $FF
; Tile index $146
.db $00 $00 $FF $FF $01 $00 $FF $FF $03 $00 $FF $FF $03 $00 $FC $FF $04 $00 $FC $FF $07 $03 $FF $FC $0E $03 $FF $FC $0F $01 $FD $FE
; Tile index $147
.db $B0 $0F $07 $F8 $FC $03 $41 $FE $B7 $48 $00 $FF $A1 $BE $A0 $5F $83 $FE $F2 $0D $43 $BE $FE $01 $D8 $7B $87 $00 $26 $CF $FF $00
; Tile index $148
.db $04 $FF $F8 $00 $02 $1D $E0 $00 $0E $CF $F2 $02 $C2 $3F $3F $C0 $EF $10 $00 $FF $C7 $38 $00 $FF $80 $7F $3E $C1 $81 $E1 $7E $00
; Tile index $149
.db $90 $77 $0F $00 $FC $03 $00 $00 $3F $C2 $03 $03 $1F $D8 $EF $0B $FC $78 $7F $87 $0C $F4 $7F $83 $6C $F0 $8F $07 $9D $F0 $1F $0F
; Tile index $14A
.db $00 $7F $FE $01 $C0 $7F $7F $80 $40 $2F $FF $C0 $B8 $1E $DF $E0 $0F $03 $EF $FC $2C $00 $F7 $FF $00 $00 $FF $FF $94 $00 $FF $FF
; Tile index $14B
.db $00 $FF $BF $40 $00 $FC $FF $00 $0F $FF $FF $00 $FE $F0 $F7 $0F $65 $00 $7F $FF $5D $00 $FF $FF $A3 $00 $FF $FF $59 $00 $FF $FF
; Tile index $14C
.db $2D $84 $FF $04 $1F $78 $FB $07 $77 $A0 $DF $FF $D9 $02 $FA $FF $55 $01 $FE $FF $21 $00 $FF $FF $55 $00 $FF $FF $56 $00 $FF $FF
; Tile index $14D
.db $FF $80 $BF $7F $F5 $00 $FF $FF $FE $00 $FF $FF $7F $80 $FF $FF $AA $54 $FF $FF $7C $08 $F7 $FF $D1 $00 $FF $FF $17 $00 $FF $FF
; Tile index $14E
.db $7D $12 $EF $FF $BD $08 $F7 $FF $57 $01 $FE $FF $55 $00 $FF $FF $AB $00 $FF $FF $1F $00 $FF $FF $FE $01 $FF $FF $FA $04 $FE $FF
; Tile index $14F
.db $BE $41 $FF $FF $FD $28 $D7 $FF $FA $00 $FF $FF $56 $00 $FE $FF $F0 $02 $F2 $FF $08 $55 $5D $FF $DB $24 $FF $FF $5D $A0 $FF $FF
; Tile index $150
.db $FF $20 $DF $FF $57 $00 $FE $FF $E0 $15 $F5 $FF $00 $AB $AB $FF $5F $A0 $FF $FF $FF $00 $FF $FF $FF $04 $FB $FF $FF $40 $BF $FF
; Tile index $151
.db $E0 $1F $CF $F0 $60 $1D $0F $F0 $A0 $1E $AD $72 $30 $48 $6F $F0 $70 $8C $AF $F0 $B0 $48 $F7 $F8 $B7 $0F $90 $F8 $18 $87 $97 $F8
; Tile index $152
.db $00 $00 $FF $00 $00 $00 $FF $00 $00 $04 $FB $04 $00 $00 $FF $00 $01 $09 $FE $00 $40 $43 $BC $00 $04 $B4 $7B $00 $00 $FF $00 $FF
; Tile index $153
.db $40 $4A $B5 $00 $20 $37 $C8 $00 $00 $2E $D1 $00 $24 $FC $03 $00 $C0 $F8 $07 $00 $08 $F8 $07 $00 $00 $0F $F0 $0F $00 $FF $00 $FF
; Tile index $154
.db $00 $C9 $3F $00 $08 $09 $F7 $00 $1B $19 $E7 $00 $10 $13 $EF $00 $79 $7A $86 $01 $A1 $AC $50 $0F $7F $80 $00 $FF $D8 $25 $00 $FF
; Tile index $155
.db $A0 $80 $BF $7F $D0 $80 $BF $7F $40 $00 $7F $FF $D0 $00 $FF $FF $F4 $00 $FF $FF $FF $00 $FF $FF $FF $00 $10 $FF $FF $00 $0D $FF
; Tile index $156
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $00 $FF $FF $FF $00 $FF $FF $FF $00 $AE $FF $FF $00 $35 $FF
; Tile index $157
.db $06 $00 $FF $FF $03 $00 $FF $FF $06 $00 $FF $FF $02 $00 $FF $FF $7F $00 $FF $FF $FF $00 $FE $FF $FF $00 $FB $FF $FF $00 $A5 $FF
; Tile index $158
.db $BB $00 $FF $FF $F2 $00 $FF $FF $BD $00 $FF $FF $B6 $00 $FF $FF $FF $00 $BE $FF $FF $00 $D7 $FF $FF $00 $29 $FF $FF $00 $D7 $FF
; Tile index $159
.db $C0 $00 $FF $FF $20 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $AA $FF $FF $00 $76 $FF $FF $00 $DB $FF
; Tile index $15A
.db $00 $00 $FF $FF $05 $00 $FF $FF $FF $00 $FF $FF $FF $00 $F7 $FF $FF $00 $AA $FF $FF $00 $D5 $FF $FF $00 $BF $FF $FF $00 $6F $FF
; Tile index $15B
.db $0F $00 $FD $FF $0F $00 $FF $FF $1F $00 $FE $FF $BB $03 $BB $FC $7B $96 $E7 $BC $0F $02 $FF $FC $0F $02 $FF $FC $0F $00 $FF $FF
; Tile index $15C
.db $FB $00 $FC $FF $FF $04 $D7 $F8 $AC $3F $36 $C5 $F9 $C6 $FE $01 $C8 $AF $76 $01 $BC $7C $83 $00 $00 $A1 $FF $00 $FF $00 $00 $FF
; Tile index $15D
.db $80 $7F $80 $00 $00 $FF $F8 $07 $C0 $3F $01 $FE $C0 $3E $1F $E0 $01 $F1 $3E $C0 $10 $D3 $EF $00 $07 $F8 $81 $7F $FF $00 $00 $FF
; Tile index $15E
.db $B1 $81 $7E $1F $B4 $60 $6F $9F $B0 $E0 $FF $1F $68 $E0 $BF $1F $F3 $00 $BF $7F $FC $00 $7F $FF $FF $00 $5F $FF $DF $00 $07 $FF
; Tile index $15F
.db $80 $00 $FF $FF $BC $00 $FF $FF $16 $00 $FF $FF $01 $00 $FF $FF $0A $00 $FF $FF $87 $07 $F8 $FF $EC $00 $FF $FF $D1 $00 $FF $FF
; Tile index $160
.db $1F $00 $FF $FF $2D $00 $FD $FF $AA $00 $FE $FF $D6 $01 $FF $FF $7F $11 $FF $EE $FA $14 $FE $D7 $FB $1C $FF $9F $FB $2C $FF $2F
; Tile index $161
.db $D9 $00 $FF $FF $C7 $00 $FF $FF $FF $00 $FF $FF $7F $02 $FD $7F $AF $B0 $FF $CF $DF $01 $FE $CF $FF $60 $EF $BF $BF $20 $FF $BF
; Tile index $162
.db $FF $00 $FF $FF $FE $01 $FF $FF $F3 $04 $F7 $FF $FE $20 $DF $FF $FA $07 $FF $FD $E9 $14 $FD $F7 $F1 $0B $FB $FE $FA $0C $FE $C5
; Tile index $163
.db $CE $19 $DF $F7 $D7 $28 $FF $FF $3A $47 $7F $FD $82 $57 $D7 $FD $4D $63 $6B $BE $2E $B3 $BF $D1 $B7 $50 $F2 $4F $E6 $0D $AE $F8
; Tile index $164
.db $F4 $09 $FD $FF $41 $AA $EB $FF $15 $00 $15 $FE $8D $56 $5F $F3 $DE $20 $E4 $3F $EE $19 $9E $F0 $E3 $9C $E0 $00 $74 $8B $00 $00
; Tile index $165
.db $FA $00 $FA $FF $66 $D4 $F2 $9F $84 $50 $D4 $7F $66 $03 $67 $F9 $7E $33 $48 $81 $7E $9F $08 $01 $80 $7B $0D $00 $00 $F6 $09 $04
; Tile index $166
.db $9E $41 $C0 $FF $80 $03 $80 $FF $00 $0F $00 $FF $00 $07 $00 $FF $E0 $FF $E0 $1F $02 $D5 $00 $FF $01 $FE $00 $FF $00 $FF $00 $FF
; Tile index $167
.db $00 $FF $00 $FF $01 $FE $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $80 $7F $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF
; Tile index $168
.db $00 $FF $00 $FF $04 $FB $00 $FF $F9 $06 $00 $FF $00 $FF $00 $FF $2B $D4 $00 $FF $3E $C1 $00 $FF $5F $A0 $00 $FF $BF $40 $00 $FF
; Tile index $169
.db $1E $E1 $00 $FF $A7 $58 $00 $FF $03 $FC $00 $FF $48 $B7 $00 $FF $F3 $04 $00 $FF $5F $A0 $00 $FF $FE $00 $00 $FF $FF $00 $00 $FF
; Tile index $16A
.db $7F $00 $02 $FF $FF $00 $09 $FF $FF $00 $0A $FF $FF $00 $03 $FF $FF $00 $05 $FF $FF $00 $05 $FF $FF $00 $02 $FF $FF $00 $09 $FF
; Tile index $16B
.db $FF $00 $44 $FF $FF $00 $A9 $FF $FF $00 $52 $FF $FF $00 $AD $FF $FF $00 $7A $FF $FF $00 $AD $FF $FF $00 $B5 $FF $FF $00 $FE $FF
; Tile index $16C
.db $FF $00 $4A $FF $FF $00 $50 $FF $FF $00 $AD $FF $FF $00 $6A $FF $FF $00 $B7 $FF $FF $00 $54 $FF $FF $00 $B5 $FF $FF $00 $D5 $FF
; Tile index $16D
.db $FF $00 $14 $FF $FF $00 $A9 $FF $FF $00 $00 $FF $FF $00 $A0 $FF $FF $00 $DD $FF $FF $00 $65 $FF $FF $00 $55 $FF $FF $00 $AD $FF
; Tile index $16E
.db $FF $00 $55 $FF $FF $00 $2A $FF $FF $00 $45 $FF $7F $00 $16 $FF $7F $00 $09 $FF $FF $00 $00 $FF $FF $00 $6B $FF $FF $00 $2A $FF
; Tile index $16F
.db $FF $00 $BF $FF $FF $00 $EF $FF $FF $00 $5B $FF $FF $00 $FF $FF $FF $00 $BF $FF $FF $00 $AB $FF $FF $00 $57 $FF $FF $00 $BD $FF
; Tile index $170
.db $00 $00 $FF $FF $00 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FA $FF $FE $00 $40 $FF $F4 $00 $B4 $FF $D7 $00 $D5 $FF $FB $00 $AA $FF
; Tile index $171
.db $00 $00 $FF $FF $57 $00 $FF $FF $FF $00 $FB $FF $FF $00 $44 $FF $F4 $00 $10 $FF $8A $00 $80 $FF $40 $00 $00 $FF $D8 $00 $40 $FF
; Tile index $172
.db $02 $00 $FF $FF $FF $00 $FF $FF $FF $00 $51 $FF $FF $00 $84 $FF $80 $00 $00 $FF $06 $00 $00 $FF $00 $04 $00 $FF $0D $32 $0D $F2
; Tile index $173
.db $FF $00 $FC $FF $FF $00 $DA $FF $FF $00 $40 $FF $FC $03 $90 $FF $50 $0B $01 $FE $0C $03 $00 $FF $01 $02 $01 $FE $40 $89 $40 $BF
; Tile index $174
.db $11 $BA $10 $EF $FF $00 $A0 $FF $FF $00 $08 $FF $0B $F4 $00 $FF $00 $FF $50 $AF $01 $7E $F5 $0A $48 $B7 $FA $05 $02 $BD $76 $89
; Tile index $175
.db $00 $FF $00 $FF $85 $7E $05 $FA $92 $2D $12 $ED $01 $F0 $00 $FF $0F $80 $07 $FF $47 $A0 $47 $BF $1C $C0 $0F $FF $1C $80 $1F $FF
; Tile index $176
.db $EF $E0 $EB $1F $4D $80 $4F $BF $2C $00 $2F $FF $E6 $09 $EF $FF $EA $1D $FF $F7 $F5 $00 $FF $FF $80 $00 $FF $FF $BE $01 $FF $FF
; Tile index $177
.db $E7 $C0 $3F $FE $CA $45 $BF $FD $88 $7D $FD $F7 $2F $D0 $FF $D0 $F5 $1A $EF $FA $3F $00 $FF $F8 $E8 $17 $FF $FF $A6 $49 $EE $FC
; Tile index $178
.db $CF $38 $FE $3B $3C $CB $FF $CB $C6 $BB $FF $39 $3E $E5 $FF $C5 $FF $09 $FF $08 $7F $84 $FF $84 $FF $30 $D0 $10 $F8 $07 $80 $00
; Tile index $179
.db $FD $62 $E3 $BF $FE $70 $72 $AF $ED $E0 $F9 $2F $FF $F5 $FF $39 $65 $7A $60 $A0 $38 $C7 $00 $00 $C0 $3F $00 $00 $00 $FE $01 $00
; Tile index $17A
.db $8F $50 $55 $FF $77 $85 $E7 $F9 $FA $5D $78 $98 $53 $AF $03 $03 $3D $FF $10 $10 $4C $FE $41 $40 $40 $E8 $17 $00 $00 $01 $FE $00
; Tile index $17B
.db $B7 $D8 $F0 $10 $72 $8F $02 $02 $14 $FF $00 $00 $DA $7F $80 $00 $00 $D4 $2B $00 $00 $25 $DA $00 $00 $10 $EF $00 $00 $00 $FF $00
; Tile index $17C
.db $00 $FF $00 $00 $00 $FE $01 $00 $00 $FF $00 $00 $00 $1F $E0 $00 $00 $37 $C8 $00 $00 $03 $FC $00 $00 $97 $68 $00 $00 $6F $90 $00
; Tile index $17D
.db $01 $F5 $0A $04 $00 $D9 $26 $00 $00 $EB $16 $00 $00 $FA $07 $00 $00 $F2 $0F $00 $00 $FC $03 $00 $00 $FB $07 $00 $00 $C7 $38 $07
; Tile index $17E
.db $02 $FD $40 $BF $04 $F9 $80 $7F $09 $F4 $80 $7F $0D $70 $80 $7F $86 $F0 $00 $7F $BF $C0 $01 $7F $7F $80 $02 $FF $3F $C0 $04 $FF
; Tile index $17F
.db $BF $40 $00 $FF $6A $15 $00 $FF $7F $00 $00 $FF $1F $00 $00 $FF $A6 $00 $00 $FF $FF $00 $50 $FF $FF $00 $45 $FF $FF $00 $90 $FF
; Tile index $180
.db $0F $F0 $00 $FF $D7 $28 $00 $FF $EB $14 $00 $FF $5C $80 $00 $FF $F3 $00 $00 $FF $7F $00 $00 $FF $FF $00 $15 $FF $DF $00 $41 $FF
; Tile index $181
.db $FF $00 $00 $FF $FF $00 $02 $FF $FB $00 $00 $FF $7E $00 $28 $FF $47 $00 $01 $FF $BF $00 $00 $FF $E3 $00 $40 $FF $A1 $00 $00 $FF
; Tile index $182
.db $FF $00 $02 $FF $FF $00 $09 $FF $FF $00 $12 $FF $FF $00 $45 $FF $FF $00 $11 $FF $FF $00 $A4 $FF $FF $00 $10 $FF $FF $00 $8A $FF
; Tile index $183
.db $FF $00 $5B $FF $FF $00 $5E $FF $FF $00 $49 $FF $FF $00 $2A $FF $FF $00 $55 $FF $FF $00 $AA $FF $FF $00 $14 $FF $FF $00 $AA $FF
; Tile index $184
.db $FF $00 $AA $FF $FF $00 $D4 $FF $FF $00 $51 $FF $FF $00 $04 $FF $FF $00 $52 $FF $FF $00 $AA $FF $FF $00 $AA $FF $FF $00 $A4 $FF
; Tile index $185
.db $FF $00 $54 $FF $FF $00 $A9 $FF $FF $00 $4A $FF $FF $00 $05 $FF $FF $00 $F1 $FF $FF $00 $9E $FF $FF $00 $8B $FF $FF $00 $24 $FF
; Tile index $186
.db $FF $00 $D6 $FF $FF $00 $2D $FF $FF $00 $F7 $FF $FF $00 $5D $FF $FF $00 $5F $FF $FF $00 $AB $FF $FF $00 $AA $FF $FF $00 $A9 $FF
; Tile index $187
.db $FF $00 $F7 $FF $FF $00 $AF $FF $FF $00 $7F $FF $FF $00 $AF $FF $FF $00 $7B $FF $FF $00 $DF $FF $FF $00 $B5 $FF $FF $00 $5F $FF
; Tile index $188
.db $FD $00 $E9 $FF $FF $00 $AA $FF $FF $00 $FD $FF $FF $00 $EF $FF $FF $00 $FD $FF $FF $00 $FF $FF $FF $00 $F6 $FF $FF $00 $DD $FF
; Tile index $189
.db $E8 $00 $28 $FF $7C $00 $44 $FF $FF $00 $BB $FF $FF $00 $56 $FF $FF $00 $FF $FF $FF $00 $ED $FF $FF $00 $B6 $FF $FF $00 $DB $FF
; Tile index $18A
.db $00 $00 $00 $FF $00 $00 $00 $FF $FE $00 $F6 $FF $FF $00 $AD $FF $FF $00 $FE $FF $FF $00 $B7 $FF $FF $00 $FE $FF $FF $00 $55 $FF
; Tile index $18B
.db $10 $00 $10 $EF $00 $00 $00 $FF $FF $00 $AD $FF $FF $00 $D6 $FF $FF $00 $BB $FF $FF $00 $DD $FF $FF $00 $EB $FF $FF $00 $BE $FF
; Tile index $18C
.db $00 $7F $00 $FF $00 $1B $00 $FF $80 $00 $00 $FF $F4 $01 $C0 $FF $FB $00 $B8 $FF $FF $00 $55 $FF $FF $00 $F4 $FF $FF $00 $D6 $FF
; Tile index $18D
.db $1D $00 $0F $FF $0F $00 $0F $FF $6F $00 $2F $FF $FF $00 $0B $FF $FF $00 $0A $FF $FF $00 $25 $FF $BF $00 $A9 $FF $FF $00 $4A $FF
; Tile index $18E
.db $7C $0B $F7 $FF $73 $00 $FF $FF $F9 $07 $FF $FF $F3 $09 $FB $FD $F9 $03 $7F $FF $FD $02 $FF $FE $F8 $01 $19 $FF $F8 $00 $A8 $FF
; Tile index $18F
.db $FF $4C $B6 $C0 $F7 $29 $FC $2A $F9 $70 $F9 $76 $BD $5A $FF $5A $D8 $21 $F9 $26 $5E $B4 $FA $B7 $39 $C1 $F9 $C6 $6F $90 $FF $90
; Tile index $190
.db $A0 $DF $40 $00 $A0 $7F $40 $00 $00 $9B $64 $00 $00 $97 $68 $00 $00 $0A $F5 $00 $00 $24 $FB $00 $00 $21 $FE $00 $00 $9F $E0 $10
; Tile index $191
.db $00 $FA $05 $00 $00 $54 $AB $00 $00 $F8 $07 $00 $00 $54 $AB $00 $00 $A2 $5D $00 $00 $5F $A0 $00 $00 $F8 $07 $00 $00 $C7 $38 $07
; Tile index $192
.db $00 $80 $7F $00 $00 $10 $FF $00 $00 $00 $FF $00 $00 $0F $F0 $00 $00 $FC $03 $00 $04 $CF $3C $03 $7F $E0 $E0 $1F $FF $00 $00 $FF
; Tile index $193
.db $00 $17 $E8 $00 $00 $1F $E0 $00 $00 $FC $03 $00 $00 $C3 $3F $00 $06 $F9 $E0 $1F $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $14 $FF
; Tile index $194
.db $00 $FC $03 $00 $00 $E1 $1E $01 $00 $1F $F0 $0F $03 $FC $00 $FF $FF $00 $00 $FF $FF $00 $09 $FF $FF $00 $AB $FF $FF $00 $2A $FF
; Tile index $195
.db $01 $3E $E0 $1F $01 $FE $00 $FF $07 $F8 $00 $FF $FF $00 $01 $FF $FF $00 $3F $FF $FF $00 $AE $FF $FF $00 $7B $FF $FF $00 $FF $FF
; Tile index $196
.db $FF $00 $32 $FF $FF $00 $11 $FF $FE $00 $4A $FF $FF $00 $B5 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $DD $FF $FF $00 $F6 $FF
; Tile index $197
.db $FF $00 $45 $FF $78 $00 $28 $FF $8F $00 $85 $FF $FB $00 $69 $FF $FF $00 $FF $FF $FF $00 $DA $FF $F0 $00 $20 $FF $82 $00 $82 $FD
; Tile index $198
.db $BF $00 $04 $FF $90 $00 $10 $FF $00 $00 $00 $FF $D2 $00 $42 $FF $FC $00 $5C $FF $0E $00 $0E $F1 $5C $00 $5C $A3 $04 $00 $04 $FF
; Tile index $199
.db $C0 $00 $00 $FF $00 $01 $00 $FF $00 $00 $00 $FF $81 $00 $81 $FF $0B $00 $0A $FF $07 $40 $46 $FF $0F $00 $0B $FF $7F $80 $FF $FF
; Tile index $19A
.db $3F $00 $11 $FF $0F $10 $00 $FF $1F $00 $15 $FF $7F $00 $5B $FF $FF $00 $FF $FF $FF $00 $FF $FF $F4 $00 $FF $FF $A5 $00 $FF $FF
; Tile index $19B
.db $FF $00 $52 $FF $FF $00 $29 $FF $FF $00 $46 $FF $FF $00 $BF $FF $FF $00 $FF $FF $FD $00 $FF $FF $00 $00 $FF $FF $04 $00 $FF $FF
; Tile index $19C
.db $FF $00 $DD $FF $FF $00 $25 $FF $FF $00 $FF $FF $FF $00 $FD $FF $FF $00 $FF $FF $25 $00 $FF $FF $88 $00 $FF $FF $22 $00 $FF $FF
; Tile index $19D
.db $FF $00 $40 $FF $F0 $00 $50 $FF $F8 $00 $E8 $FF $FD $00 $FD $FF $FF $00 $FF $FF $FB $00 $FF $FF $04 $00 $FF $FF $11 $00 $FF $FF
; Tile index $19E
.db $FF $00 $BE $FF $7F $00 $01 $FF $0F $00 $00 $FF $01 $00 $00 $FF $FA $00 $FA $FF $FF $00 $FF $FF $57 $00 $FF $FF $2D $00 $FF $FF
; Tile index $19F
.db $FF $00 $81 $FF $FF $00 $6E $FF $FF $00 $9B $FF $FF $00 $07 $FF $BF $00 $88 $FF $FF $00 $77 $FF $FF $00 $FD $FF $7F $00 $FF $FF
