.BANK 2 SLOT 2
.ORG $0000

.section "splash" superfree
splash__palette__bin:
	.incbin "banks/bank2/splash (palette).bin"
splash__tilemap__stmcompr:
	.incbin "banks/bank2/splash (tilemap).stmcompr"
splash__tiles__psgcompr:
	.incbin "banks/bank2/splash (tiles).psgcompr"
.ends


.BANK 3 SLOT 2
.ORG $0000

.section "VanHalenTitleGap" free
VanHalenTitleGap__palette__bin:
	.incbin "banks/bank3/VanHalenTitleGap (palette).bin"
VanHalenTitleGap__tilemap__stmc:
	.incbin "banks/bank3/VanHalenTitleGap (tilemap).stmcompr"
VanHalenTitleGap__tiles__psgcom:
	.incbin "banks/bank3/VanHalenTitleGap (tiles).psgcompr"

VanHalenTitleTop__palette__bin:
	.incbin "banks/bank3/VanHalenTitleTop (palette).bin"
VanHalenTitleTop__tilemap__stmc:
	.incbin "banks/bank3/VanHalenTitleTop (tilemap).stmcompr"
VanHalenTitleTop__tiles__psgcom:
	.incbin "banks/bank3/VanHalenTitleTop (tiles).psgcompr"
.ends


.BANK 4 SLOT 2
.ORG $0000
VanHalen1978__palette__bin:
	.incbin "banks/bank4/VanHalen1978 (palette).bin"
VanHalen1978__tilemap__stmcompr:
	.incbin "banks/bank4/VanHalen1978 (tilemap).stmcompr"
VanHalen1978__tiles__psgcompr:
	.incbin "banks/bank4/VanHalen1978 (tiles).psgcompr"


.BANK 5 SLOT 2
.ORG $0000
VanHalen1979__palette__bin:
	.incbin "banks/bank5/VanHalen1979 (palette).bin"
VanHalen1979__tilemap__stmcompr:
	.incbin "banks/bank5/VanHalen1979 (tilemap).stmcompr"
VanHalen1979__tiles__psgcompr:
	.incbin "banks/bank5/VanHalen1979 (tiles).psgcompr"


.BANK 6 SLOT 2
.ORG $0000
VanHalen1980__palette__bin:
	.incbin "banks/bank6/VanHalen1980 (palette).bin"
VanHalen1980__tilemap__stmcompr:
	.incbin "banks/bank6/VanHalen1980 (tilemap).stmcompr"
VanHalen1980__tiles__psgcompr:
	.incbin "banks/bank6/VanHalen1980 (tiles).psgcompr"


.BANK 7 SLOT 2
.ORG $0000
VanHalen1981__palette__bin:
	.incbin "banks/bank7/VanHalen1981 (palette).bin"
VanHalen1981__tilemap__stmcompr:
	.incbin "banks/bank7/VanHalen1981 (tilemap).stmcompr"
VanHalen1981__tiles__psgcompr:
	.incbin "banks/bank7/VanHalen1981 (tiles).psgcompr"


.BANK 8 SLOT 2
.ORG $0000
VanHalen1982__palette__bin:
	.incbin "banks/bank8/VanHalen1982 (palette).bin"
VanHalen1982__tilemap__stmcompr:
	.incbin "banks/bank8/VanHalen1982 (tilemap).stmcompr"
VanHalen1982__tiles__psgcompr:
	.incbin "banks/bank8/VanHalen1982 (tiles).psgcompr"


.BANK 9 SLOT 2
.ORG $0000
VanHalen1984__palette__bin:
	.incbin "banks/bank9/VanHalen1984 (palette).bin"
VanHalen1984__tilemap__stmcompr:
	.incbin "banks/bank9/VanHalen1984 (tilemap).stmcompr"
VanHalen1984__tiles__psgcompr:
	.incbin "banks/bank9/VanHalen1984 (tiles).psgcompr"


.BANK 10 SLOT 2
.ORG $0000
VanHalen1986__palette__bin:
	.incbin "banks/bank10/VanHalen1986 (palette).bin"
VanHalen1986__tilemap__stmcompr:
	.incbin "banks/bank10/VanHalen1986 (tilemap).stmcompr"
VanHalen1986__tiles__psgcompr:
	.incbin "banks/bank10/VanHalen1986 (tiles).psgcompr"


.BANK 11 SLOT 2
.ORG $0000
VanHalen1988__palette__bin:
	.incbin "banks/bank11/VanHalen1988 (palette).bin"
VanHalen1988__tilemap__stmcompr:
	.incbin "banks/bank11/VanHalen1988 (tilemap).stmcompr"
VanHalen1988__tiles__psgcompr:
	.incbin "banks/bank11/VanHalen1988 (tiles).psgcompr"


.BANK 12 SLOT 2
.ORG $0000
VanHalen1991__palette__bin:
	.incbin "banks/bank12/VanHalen1991 (palette).bin"
VanHalen1991__tilemap__stmcompr:
	.incbin "banks/bank12/VanHalen1991 (tilemap).stmcompr"
VanHalen1991__tiles__psgcompr:
	.incbin "banks/bank12/VanHalen1991 (tiles).psgcompr"


.BANK 13 SLOT 2
.ORG $0000
VanHalen1995__palette__bin:
	.incbin "banks/bank13/VanHalen1995 (palette).bin"
VanHalen1995__tilemap__stmcompr:
	.incbin "banks/bank13/VanHalen1995 (tilemap).stmcompr"
VanHalen1995__tiles__psgcompr:
	.incbin "banks/bank13/VanHalen1995 (tiles).psgcompr"


.BANK 14 SLOT 2
.ORG $0000
VanHalen1998__palette__bin:
	.incbin "banks/bank14/VanHalen1998 (palette).bin"
VanHalen1998__tilemap__stmcompr:
	.incbin "banks/bank14/VanHalen1998 (tilemap).stmcompr"
VanHalen1998__tiles__psgcompr:
	.incbin "banks/bank14/VanHalen1998 (tiles).psgcompr"


.BANK 15 SLOT 2
.ORG $0000
VanHalen2012__palette__bin:
	.incbin "banks/bank15/VanHalen2012 (palette).bin"
VanHalen2012__tilemap__stmcompr:
	.incbin "banks/bank15/VanHalen2012 (tilemap).stmcompr"
VanHalen2012__tiles__psgcompr:
	.incbin "banks/bank15/VanHalen2012 (tiles).psgcompr"