M:cursor_manager
F:G$engine_cursor_manager_init$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lcursor_manager.engine_cursor_manager_init$index$1$22({1}SC:U),B,1,4
S:Lcursor_manager.engine_cursor_manager_init$co$1$23({2}DG,STtag_struct_cursor_object:S),R,0,0,[c,b]
F:G$engine_cursor_manager_load$0$0({2}DF,SV:S),Z,0,2,0,0,0
S:Lcursor_manager.engine_cursor_manager_load$offset$1$24({1}SC:U),B,1,4
S:Lcursor_manager.engine_cursor_manager_load$idx$1$25({1}SC:U),R,0,0,[e]
S:Lcursor_manager.engine_cursor_manager_load$fx$1$25({1}SC:U),R,0,0,[c]
S:Lcursor_manager.engine_cursor_manager_load$fy$1$25({1}SC:U),B,1,-4
S:Lcursor_manager.engine_cursor_manager_load$vx$1$25({1}SC:U),R,0,0,[b]
S:Lcursor_manager.engine_cursor_manager_load$vy$1$25({1}SC:U),B,1,-3
S:Lcursor_manager.engine_cursor_manager_load$text$1$25({2}DG,SC:U),R,0,0,[e,d]
S:Lcursor_manager.engine_cursor_manager_load$sloc0$1$0({2}DC,SC:U),B,1,-2
F:G$engine_cursor_manager_save$0$0({2}DF,SC:U),Z,0,0,0,0,0
S:Lcursor_manager.engine_cursor_manager_save$co$1$30({2}DG,STtag_struct_cursor_object:S),R,0,0,[]
F:G$engine_cursor_manager_draw$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lcursor_manager.engine_cursor_manager_draw$co$1$31({2}DG,STtag_struct_cursor_object:S),R,0,0,[]
S:Lcursor_manager.engine_cursor_manager_draw$x$1$31({1}SC:U),R,0,0,[c]
S:Lcursor_manager.engine_cursor_manager_draw$y$1$31({1}SC:U),R,0,0,[b]
S:Lcursor_manager.engine_cursor_manager_draw$tile$1$31({2}SI:U),R,0,0,[]
S:Lcursor_manager.engine_cursor_manager_draw$sloc0$1$0({1}SC:U),B,1,-2
S:Lcursor_manager.engine_cursor_manager_draw$sloc1$1$0({1}SC:U),B,1,-4
S:Lcursor_manager.engine_cursor_manager_draw$sloc2$1$0({1}SC:U),B,1,-3
S:Lcursor_manager.engine_cursor_manager_draw$sloc3$1$0({1}SC:U),B,1,-1
F:G$engine_cursor_manager_decX$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lcursor_manager.engine_cursor_manager_decX$co$1$32({2}DG,STtag_struct_cursor_object:S),R,0,0,[c,b]
F:G$engine_cursor_manager_incX$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lcursor_manager.engine_cursor_manager_incX$co$1$35({2}DG,STtag_struct_cursor_object:S),R,0,0,[c,b]
F:G$engine_cursor_manager_decY$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lcursor_manager.engine_cursor_manager_decY$co$1$38({2}DG,STtag_struct_cursor_object:S),R,0,0,[]
F:G$engine_cursor_manager_incY$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lcursor_manager.engine_cursor_manager_incY$co$1$41({2}DG,STtag_struct_cursor_object:S),R,0,0,[]
F:Fcursor_manager$update_values$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lcursor_manager.update_values$co$1$44({2}DG,STtag_struct_cursor_object:S),R,0,0,[]
S:Lcursor_manager.update_values$grid_x$1$44({1}SC:U),R,0,0,[c]
S:Lcursor_manager.update_values$grid_y$1$44({1}SC:U),R,0,0,[e]
T:Fcursor_manager$tag_struct_cursor_object[({0}S:S$cursor_index_x$0$0({1}SC:U),Z,0,0)({1}S:S$cursor_index_y$0$0({1}SC:U),Z,0,0)({2}S:S$cursor_value_x$0$0({1}SC:U),Z,0,0)({3}S:S$cursor_value_y$0$0({1}SC:U),Z,0,0)]
S:G$cursor_album$0$0({24}DA12d,DG,SC:U),E,0,0
S:G$global_cursor_object$0$0({4}STtag_struct_cursor_object:S),E,0,0
S:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollX$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_SRAM$0$0({2}DF,DG,SC:U),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_False$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_True$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGPaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTilePriority$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_PRIORITY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_USE_SPRITE_PALETTE$0$0({2}DF,SI:U),C,0,0
