M:screen_manager
F:G$engine_screen_manager_init$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscreen_manager.engine_screen_manager_init$open_screen_type$1$10({1}SC:U),B,1,4
F:G$engine_screen_manager_update$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Fscreen_manager$curr_screen_type$0$0({1}SC:U),E,0,0
S:Fscreen_manager$next_screen_type$0$0({1}SC:U),E,0,0
S:Fscreen_manager$load_method$0$0({14}DA7d,DC,DF,SV:S),E,0,0
S:Fscreen_manager$update_method$0$0({14}DA7d,DC,DF,SV:S),E,0,0
S:G$screen_none_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_none_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_splash_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_splash_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_title_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_title_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_scroll_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_scroll_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_select_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_select_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_record_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_record_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_test_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_test_screen_update$0$0({2}DF,SV:S),C,0,0
