M:storage_manager
F:G$engine_storage_manager_available$0$0({2}DF,SC:U),Z,0,0,0,0,0
S:Lstorage_manager.engine_storage_manager_available$savegame$1$18({2}DG,STtag_struct_storage_object:S),R,0,0,[l,h]
S:Lstorage_manager.engine_storage_manager_available$foundMagic$1$18({1}SC:U),R,0,0,[l]
F:G$engine_storage_manager_read$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lstorage_manager.engine_storage_manager_read$savegame$1$19({2}DG,STtag_struct_storage_object:S),R,0,0,[c,b]
S:Lstorage_manager.engine_storage_manager_read$ro$1$19({2}DG,STtag_struct_record_object:S),R,0,0,[]
F:G$engine_storage_manager_write$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lstorage_manager.engine_storage_manager_write$savegame$1$20({2}DG,STtag_struct_storage_object:S),R,0,0,[c,b]
S:Lstorage_manager.engine_storage_manager_write$ro$1$20({2}DG,STtag_struct_record_object:S),R,0,0,[]
F:G$engine_storage_manager_erase$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lstorage_manager.engine_storage_manager_erase$savegame$1$21({2}DG,STtag_struct_storage_object:S),R,0,0,[c,b]
T:Fstorage_manager$tag_struct_storage_object[({0}S:S$Magic$0$0({4}SL:U),Z,0,0)({4}S:S$save_album_index$0$0({1}SC:U),Z,0,0)({5}S:S$terminal$0$0({1}SC:U),Z,0,0)]
T:Fstorage_manager$tag_struct_record_object[({0}S:S$record_album_index$0$0({1}SC:U),Z,0,0)]
S:G$record_tiles_data$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$record_tilemap_data$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$record_palette_data$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$global_record_object$0$0({1}STtag_struct_record_object:S),E,0,0
S:G$global_savegame_object$0$0({6}STtag_struct_storage_object:S),E,0,0
S:G$engine_record_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_record_manager_load$0$0({2}DF,SV:S),C,0,0
S:G$engine_record_manager_decrement$0$0({2}DF,SV:S),C,0,0
S:G$engine_record_manager_increment$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollX$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_SRAM$0$0({2}DF,DG,SC:U),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_False$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_True$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGPaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTilePriority$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_PRIORITY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_USE_SPRITE_PALETTE$0$0({2}DF,SI:U),C,0,0
