; Tile index $000
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $001
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $01 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $002
.db $FF $FF $40 $40 $FF $FF $00 $00 $FF $FB $64 $60 $3F $FF $C0 $00 $7F $FF $C0 $40 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $003
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $DF $20 $00 $FF $FB $04 $00 $FF $FF $80 $80 $FF $FF $00 $00 $FF $FF $12 $12 $FF $FF $00 $00
; Tile index $004
.db $FF $FF $00 $00 $FF $FB $04 $00 $FF $7F $8E $0E $F3 $FF $0E $02 $F7 $FF $1B $13 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $005
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $21 $21 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $006
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $01 $FF $FF $00 $00 $FF $FF $10 $10 $FF $FF $00 $00
; Tile index $007
.db $FF $FF $00 $00 $FF $FF $00 $00 $EB $FF $3C $28 $CB $FF $3C $08 $DB $FF $36 $12 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $008
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $20 $20
; Tile index $009
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $00A
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $03 $03 $FE $FF $01 $00 $FE $FF $03 $03 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $00B
.db $FF $FF $00 $00 $FF $FF $00 $00 $BF $DF $60 $00 $BF $FF $C0 $C0 $BF $FF $60 $20 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $00C
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $40 $40 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $00D
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $0B $0B $FD $FF $07 $05 $FB $FF $07 $03 $FF $FF $08 $08 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $00E
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $40 $40 $FF $FF $00 $00 $FF $FF $80 $80 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $00F
.db $FF $FF $00 $00 $FF $FF $00 $00 $EF $F7 $18 $00 $EF $FF $18 $08 $E7 $FF $18 $00 $FF $7F $8C $0C $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $010
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $F7 $08 $00 $FF $7F $80 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $011
.db $FF $FF $00 $00 $FF $FF $00 $00 $BF $DF $E0 $80 $7F $FF $C0 $40 $7F $FF $E0 $60 $FF $FF $40 $40 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $012
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $06 $06 $FD $FF $07 $05 $FB $FF $05 $01 $FF $FF $04 $04 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $013
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $80 $7F $FF $80 $00 $7F $FF $80 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $014
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FC $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $015
.db $FF $FF $00 $00 $FF $FF $00 $00 $FD $FF $00 $00 $B7 $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $DF $FF $00 $00
; Tile index $016
.db $FF $FF $00 $00 $DB $FF $00 $00 $7F $F7 $48 $40 $76 $FF $78 $70 $F7 $FF $68 $60 $FF $FF $28 $28 $FE $FF $00 $00 $FF $FF $00 $00
; Tile index $017
.db $FF $FF $00 $00 $FF $FF $02 $02 $FF $FF $20 $20 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $018
.db $FF $FF $40 $40 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $08 $08 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $019
.db $FF $FF $00 $00 $FF $FF $40 $40 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $01A
.db $FF $FF $00 $00 $FF $FF $01 $01 $FF $FF $20 $20 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $01B
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $24 $24 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $01C
.db $FF $FF $00 $00 $FF $FF $10 $10 $FF $FF $00 $00 $FF $FF $02 $02 $FF $FF $40 $40 $FF $FF $08 $08 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $01D
.db $FF $FF $00 $00 $FF $FF $01 $01 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $01E
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $12 $12 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $01F
.db $FF $FF $01 $01 $FF $FF $00 $00 $FF $FF $80 $80 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $04 $04
; Tile index $020
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $04 $04 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $021
.db $FF $FF $04 $04 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $41 $41 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $022
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $20 $20 $FF $FF $00 $00
; Tile index $023
.db $FF $FF $08 $08 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $024
.db $FF $FF $00 $00 $FF $FF $01 $01 $FF $FF $80 $80 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $025
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $F7 $FF $00 $00 $FF $FF $00 $00 $FE $FF $00 $00 $F7 $FF $00 $00 $FE $FF $00 $00
; Tile index $026
.db $F7 $FF $00 $00 $BF $FF $00 $00 $FF $FF $00 $00 $77 $FF $00 $00 $FF $FF $00 $00 $BD $FF $00 $00 $FF $FF $00 $00 $B7 $FF $00 $00
; Tile index $027
.db $FD $FF $00 $00 $FE $FF $00 $00 $7B $FF $00 $00 $D5 $FF $00 $00 $7F $FF $00 $00 $95 $FF $00 $00 $6B $FF $00 $00 $FF $FF $00 $00
; Tile index $028
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $01
; Tile index $029
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $80 $FF $FF $04 $04 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $20 $20
; Tile index $02A
.db $FF $FF $80 $80 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $40 $40 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $02B
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $08 $08 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $02C
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $80 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $02D
.db $FF $FF $80 $80 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $01 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $02E
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $10 $10 $FF $FF $02 $02 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $04 $04 $FF $FF $20 $20
; Tile index $02F
.db $FF $FF $04 $04 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $81 $81
; Tile index $030
.db $FF $FF $80 $80 $FF $FF $04 $04 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $08 $08 $FF $FF $20 $20
; Tile index $031
.db $FF $FF $40 $40 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $04 $04 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $032
.db $FB $FF $00 $00 $FA $FF $00 $00 $FF $FF $00 $00 $F7 $FF $00 $00 $FF $FF $00 $00 $FD $FF $00 $00 $D7 $FF $00 $00 $FF $FF $00 $00
; Tile index $033
.db $EF $FF $00 $00 $FB $FF $00 $00 $BF $FF $00 $00 $EE $FF $00 $00 $7B $FF $00 $00 $FE $FF $00 $00 $B7 $FF $00 $00 $ED $FF $00 $00
; Tile index $034
.db $55 $FF $00 $00 $DB $FF $00 $00 $75 $FF $00 $00 $DE $FF $00 $00 $BB $FF $00 $00 $DE $FF $00 $00 $B3 $FF $00 $00 $5A $FF $00 $00
; Tile index $035
.db $01 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $036
.db $FF $FF $00 $00 $FF $FF $04 $04 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $02 $02 $FF $FF $00 $00 $FF $FF $10 $10
; Tile index $037
.db $FF $FF $00 $00 $FF $FF $20 $20 $FF $FF $04 $04 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $038
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $40 $40
; Tile index $039
.db $FF $FF $01 $01 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $20 $20 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $03A
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $01 $FF $FF $00 $00 $FF $FF $80 $80 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $03B
.db $FF $FF $00 $00 $FF $FF $02 $02 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $01 $FF $FF $10 $10 $FF $FF $00 $00
; Tile index $03C
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $02 $02 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $03D
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $08 $08 $FF $FF $80 $80 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $03E
.db $FF $FF $04 $04 $FF $FF $00 $00 $FF $FF $10 $10 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $03F
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $10 $10 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $02 $02 $FF $FF $00 $00
; Tile index $040
.db $FF $FF $08 $08 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $80 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $041
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $10 $10 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $042
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $80 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $043
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $DB $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FA $FF $00 $00
; Tile index $044
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $75 $FF $00 $00 $FE $FF $00 $00
; Tile index $045
.db $EB $FF $00 $00 $FF $FF $00 $00 $77 $FF $00 $00 $EE $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $F4 $FF $00 $00 $DB $FF $00 $00
; Tile index $046
.db $FF $FF $00 $00 $FD $FF $00 $00 $EB $FF $00 $00 $2F $FF $00 $00 $AF $FF $00 $00 $5B $FF $00 $00 $FF $FF $00 $00 $AF $FF $00 $00
; Tile index $047
.db $6F $FF $00 $00 $57 $FF $00 $00 $F5 $FF $00 $00 $AF $FF $00 $00 $F5 $FF $00 $00 $D7 $FF $00 $00 $6D $FF $00 $00 $DA $FF $00 $00
; Tile index $048
.db $00 $00 $00 $00 $00 $00 $00 $00 $01 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $049
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $12 $12 $FC $FF $03 $01 $FE $FD $03 $01 $FF $FF $01 $01 $FF $FF $10 $10
; Tile index $04A
.db $FF $FF $24 $24 $FF $FF $00 $00 $FF $FF $00 $00 $FF $EB $54 $40 $00 $FF $FF $FF $A3 $58 $FF $FF $55 $A2 $FF $FF $EE $91 $FF $FF
; Tile index $04B
.db $FF $FF $00 $00 $FF $FF $04 $04 $FF $FF $00 $00 $FF $FF $91 $91 $00 $FF $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FB $04 $FF $FF
; Tile index $04C
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $29 $29 $00 $FF $FF $FF $D0 $2F $FF $FF $F4 $0B $FF $FF $FD $02 $FF $FF
; Tile index $04D
.db $FF $FF $00 $00 $FF $FF $84 $84 $FF $FF $00 $00 $FF $FF $24 $24 $00 $FF $FF $FB $02 $FF $FF $E2 $01 $FF $FF $F9 $A1 $5F $FF $FF
; Tile index $04E
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $94 $94 $00 $FF $FF $FF $03 $FC $FF $7F $07 $F8 $FF $3F $E1 $DE $DF $FF
; Tile index $04F
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $92 $92 $00 $FF $FF $FF $60 $9F $FF $FF $FD $02 $FF $FF $FF $00 $FF $FF
; Tile index $050
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $94 $94 $01 $FE $FF $FE $02 $FD $FF $F3 $41 $BE $FF $FB $65 $9A $FB $FD
; Tile index $051
.db $FF $FF $00 $00 $FF $FF $80 $80 $FF $FF $00 $00 $FF $FF $02 $02 $FE $FF $01 $00 $7E $FF $C1 $C0 $71 $C3 $9C $E0 $CC $C7 $34 $FC
; Tile index $052
.db $FF $FF $08 $08 $FF $FF $00 $00 $FF $FF $00 $00 $FF $7B $A4 $20 $00 $FF $FF $FF $02 $FF $FF $BA $01 $FF $FF $BD $A0 $FF $FF $EE
; Tile index $053
.db $FF $FF $80 $80 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $48 $48 $00 $FF $FF $FF $0F $F0 $FF $FF $0B $F4 $FF $3F $E7 $98 $9F $FF
; Tile index $054
.db $FF $FF $80 $80 $FF $FF $10 $10 $FF $FF $00 $00 $FF $FF $02 $02 $00 $FF $FF $FD $FC $03 $FF $FF $FE $00 $FF $FF $FE $01 $FF $FF
; Tile index $055
.db $FF $FF $00 $00 $FF $FF $08 $08 $FF $FF $40 $40 $FF $FF $00 $00 $19 $E3 $ED $F1 $35 $CC $FE $BD $21 $92 $FF $FF $2F $2C $D3 $FF
; Tile index $056
.db $FF $FF $80 $80 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $00 $FF $FF $F6 $88 $77 $FF $FF $F0 $0F $FF $FF $FD $02 $FE $FF
; Tile index $057
.db $FF $FF $10 $10 $FF $FF $80 $80 $FF $FF $04 $04 $FF $FF $00 $00 $3F $C5 $C6 $BC $09 $F6 $FF $FE $32 $CF $D0 $FF $00 $EF $F0 $FF
; Tile index $058
.db $FF $FF $04 $04 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $40 $40 $FC $FF $07 $04 $FB $FC $17 $17 $0E $B1 $CF $07 $75 $8A $AF $CF
; Tile index $059
.db $FF $FF $80 $80 $FF $FF $00 $00 $FF $FF $08 $08 $FF $FF $00 $00 $00 $FF $FF $00 $D0 $2F $FF $FF $28 $D7 $FF $FF $94 $6B $FF $FF
; Tile index $05A
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $80 $FF $FF $00 $00 $00 $FF $FF $00 $00 $FF $FF $F0 $00 $FF $FF $F8 $06 $FB $FB $FE
; Tile index $05B
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $A0 $FF $00 $00 $28 $D7 $D7 $28 $BF $40 $7F $FF $97 $E8 $FF $FF $6F $D0 $DF $7F
; Tile index $05C
.db $FF $FF $00 $00 $FF $FF $00 $00 $FB $FF $00 $00 $00 $FF $00 $00 $10 $FF $FF $10 $80 $3F $FF $FF $E0 $0F $FF $FF $E8 $17 $FF $FF
; Tile index $05D
.db $FF $FF $00 $00 $FF $FF $00 $00 $B7 $FF $00 $00 $10 $FF $00 $00 $10 $FF $FF $10 $08 $FF $FF $E9 $04 $FF $FF $F4 $06 $FB $FB $FE
; Tile index $05E
.db $FF $FF $00 $00 $FE $FF $00 $00 $D0 $FF $00 $00 $00 $FF $00 $00 $00 $FF $FF $00 $7F $80 $FF $FF $16 $E9 $FF $FF $4F $B0 $BF $7F
; Tile index $05F
.db $F9 $FF $00 $00 $F6 $FF $00 $00 $10 $FF $00 $00 $00 $FF $00 $00 $02 $FF $FE $02 $83 $7F $FC $FC $E6 $1F $F8 $F8 $99 $6F $F8 $F8
; Tile index $060
.db $5F $FF $00 $00 $B7 $FF $00 $00 $7F $FF $00 $00 $AF $FF $00 $00 $FB $FF $00 $00 $FF $FF $00 $00 $FD $FF $00 $00 $FF $FF $00 $00
; Tile index $061
.db $FF $FF $00 $00 $FF $FF $04 $04 $FF $FE $01 $00 $FF $FF $00 $00 $FF $FF $20 $20 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $062
.db $B9 $C0 $7F $3F $E5 $D9 $3E $0F $FA $F7 $0D $03 $FF $D8 $29 $0F $EE $F8 $0F $0F $F7 $F4 $8F $87 $FD $DE $23 $01 $FC $F7 $09 $01
; Tile index $063
.db $80 $00 $FF $FF $F5 $FF $00 $FF $F7 $F7 $08 $FF $00 $00 $FF $FF $07 $00 $FF $FF $43 $10 $FF $FF $E1 $00 $FF $FF $FB $00 $FF $FF
; Tile index $064
.db $00 $00 $FF $FF $71 $DF $04 $FF $FF $FF $00 $FF $7E $5A $A5 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $065
.db $05 $07 $FA $FF $0D $F7 $00 $FF $DC $FD $22 $FF $BD $B5 $4A $FF $C2 $00 $FF $FF $C5 $10 $FF $FF $F1 $00 $FF $FF $FF $00 $FF $FF
; Tile index $066
.db $96 $76 $29 $FF $80 $FF $00 $FF $50 $FF $AA $FF $F9 $50 $AF $FF $3E $59 $D9 $FF $2D $D6 $DE $E5 $C7 $7D $AF $F1 $C3 $1C $FC $FB
; Tile index $067
.db $AB $AB $54 $FF $20 $D4 $00 $FF $01 $FE $00 $FF $FF $BF $40 $FF $3F $00 $FF $FF $1F $00 $FF $FF $87 $40 $7F $FF $8F $00 $7F $FF
; Tile index $068
.db $D8 $87 $7F $FD $33 $84 $BC $7F $5D $02 $3E $FF $F6 $41 $BF $FF $6E $11 $FF $FF $CB $04 $FF $FF $97 $08 $FF $FF $FF $10 $EF $FF
; Tile index $069
.db $4B $7C $81 $FE $ED $FC $02 $FF $F8 $3F $40 $FF $AB $3F $40 $FF $E4 $0F $30 $FF $64 $8F $B0 $FF $BC $4F $D0 $FF $BD $4F $D0 $FF
; Tile index $06A
.db $02 $FF $7C $3F $24 $7F $BA $3F $CC $BB $8B $8F $87 $08 $72 $81 $CC $AF $50 $80 $9C $DD $22 $C0 $9F $AF $60 $C0 $8F $EF $30 $E0
; Tile index $06B
.db $C4 $24 $3B $FF $42 $BD $00 $FF $00 $FD $00 $FF $40 $FF $80 $FF $C0 $3E $BB $7F $7F $01 $BE $01 $C6 $F3 $0B $03 $F4 $F7 $0B $03
; Tile index $06C
.db $77 $00 $FF $FF $BB $00 $7F $FF $FF $00 $7F $FF $77 $00 $FF $FF $9E $60 $FF $FF $6F $91 $BE $FF $07 $F3 $FC $3F $97 $E3 $EC $9F
; Tile index $06D
.db $BF $38 $C7 $FF $BF $38 $C7 $FF $F6 $F1 $0F $FF $7F $74 $8B $FF $FC $F2 $0F $FF $FF $E0 $1F $FF $FF $C0 $3F $FF $FF $C0 $3F $FF
; Tile index $06E
.db $D1 $01 $FE $FF $F1 $04 $F8 $FF $7A $1C $E0 $FF $E8 $0F $F0 $FF $78 $3F $C0 $FF $3C $3F $C0 $FF $BA $3F $C0 $FF $FC $7F $80 $FF
; Tile index $06F
.db $20 $FF $00 $FF $00 $3F $00 $FF $01 $0F $00 $FF $00 $A7 $00 $FF $03 $FD $08 $FF $4F $C0 $1F $E0 $D0 $CD $22 $C0 $A9 $CE $51 $80
; Tile index $070
.db $3F $C0 $0F $FF $3F $E0 $1F $FF $7F $C0 $3F $FF $7F $C0 $3F $FF $6F $00 $FF $FF $CA $55 $BF $7F $0F $F0 $FF $7F $07 $F8 $FF $FF
; Tile index $071
.db $EB $0B $F4 $FF $52 $00 $E0 $FF $CC $30 $C0 $FF $8A $0A $F5 $FF $A8 $40 $FF $FF $FF $00 $FF $FF $FA $00 $FF $FF $FD $00 $FF $FF
; Tile index $072
.db $A3 $FA $0C $FF $B3 $0D $00 $FF $49 $B7 $00 $FF $5E $D0 $2F $FF $C2 $07 $FD $FF $81 $0E $FE $FF $49 $00 $FE $FF $D0 $01 $FF $FF
; Tile index $073
.db $A9 $C0 $1F $FF $31 $FD $4A $FF $DA $7F $25 $FF $D7 $01 $FE $FF $76 $88 $89 $FF $7E $81 $81 $FF $30 $DF $DF $F0 $0B $F4 $F4 $FF
; Tile index $074
.db $BD $00 $FF $FF $50 $D8 $AF $FF $EF $EF $10 $FF $DC $00 $FF $FF $44 $00 $FF $FF $7F $80 $FF $FF $3F $C0 $FF $FF $BF $00 $7F $FF
; Tile index $075
.db $F2 $07 $FD $FF $00 $00 $FF $FF $F5 $FD $0A $FF $78 $00 $FF $FF $00 $16 $FF $FF $F0 $05 $FF $FF $F2 $03 $FD $FF $FC $00 $FF $FF
; Tile index $076
.db $8F $C0 $7F $FF $01 $00 $FF $FF $50 $7B $AF $FE $BB $01 $FD $FF $20 $DF $DF $FF $13 $2D $EF $FF $02 $7F $FE $F6 $6A $97 $FC $F8
; Tile index $077
.db $FB $1F $F0 $F0 $33 $DF $E0 $C0 $AF $7F $80 $00 $8B $7F $80 $00 $AF $7F $80 $00 $FF $FF $00 $00 $BF $FF $00 $00 $FF $FF $00 $00
; Tile index $078
.db $FF $FF $00 $00 $77 $FF $00 $00 $EF $FF $00 $00 $BB $FF $00 $00 $D7 $FF $00 $00 $EA $FF $00 $00 $AF $FF $00 $00 $5B $FF $00 $00
; Tile index $079
.db $01 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $01 $00 $00 $00 $00 $00 $00 $00
; Tile index $07A
.db $FF $FF $00 $00 $FF $FF $08 $08 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $07B
.db $FF $FF $00 $00 $FF $FD $02 $00 $FF $FF $80 $80 $FF $FF $00 $00 $FF $FF $10 $10 $FF $FF $02 $02 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $07C
.db $0F $CF $F0 $7F $4F $AF $70 $1F $BB $D9 $36 $1F $C7 $6A $BD $1F $EF $F0 $1F $1F $F7 $D8 $2F $0F $EB $FC $0F $0F $F5 $FE $07 $07
; Tile index $07D
.db $FE $FF $00 $FF $FE $FF $00 $FF $FE $4A $B5 $FF $DF $84 $7B $FF $1F $10 $EF $FF $87 $10 $FF $FF $E7 $04 $FB $FF $8A $08 $F7 $FF
; Tile index $07E
.db $DE $FF $00 $FF $FF $FF $00 $FF $B9 $A9 $56 $FF $EA $00 $FF $FF $EF $00 $FF $FF $F3 $00 $FF $FF $FF $11 $EE $FF $FF $AD $52 $FF
; Tile index $07F
.db $D7 $FF $00 $FF $FD $FF $00 $FF $14 $14 $EB $FF $E3 $43 $BC $FF $D1 $01 $FE $FF $F0 $01 $FF $FF $FF $01 $FE $FF $FF $75 $8A $FF
; Tile index $080
.db $80 $FF $00 $FF $40 $FF $00 $FF $D3 $03 $FC $FF $D2 $2A $05 $FF $60 $BF $FF $27 $76 $19 $B9 $D7 $1F $FC $BC $CF $0D $3D $F2 $FF
; Tile index $081
.db $06 $D5 $03 $FF $0A $E4 $03 $FF $F3 $FC $0B $FF $7C $54 $AB $FF $78 $80 $FF $FF $B8 $C1 $7F $FF $2E $60 $9F $FF $BD $BF $40 $FF
; Tile index $082
.db $DE $17 $E8 $FF $DF $2F $E0 $FF $6D $8B $F4 $FF $EF $03 $F4 $FF $57 $05 $FA $FF $10 $04 $FF $FF $09 $22 $FD $FF $45 $81 $FE $FF
; Tile index $083
.db $73 $EB $04 $F0 $9F $C7 $28 $F0 $5B $F3 $04 $F8 $A5 $FB $0C $F8 $4D $F8 $03 $FC $8E $FF $02 $FE $FE $FC $01 $FE $D5 $FD $03 $FF
; Tile index $084
.db $F1 $FE $06 $03 $F8 $FF $07 $06 $F2 $DF $2F $06 $F7 $FD $0F $0D $C7 $F8 $1F $08 $E7 $DC $3F $14 $07 $3E $FF $16 $6B $56 $B7 $3A
; Tile index $085
.db $63 $F3 $FC $6F $3F $CF $E0 $9F $7F $9F $A0 $5F $9F $6F $50 $BF $9F $DE $E1 $BF $DD $1D $A2 $7F $FE $7F $81 $7E $C5 $7C $03 $FE
; Tile index $086
.db $FF $80 $7F $FF $7F $40 $BF $FF $FF $00 $FF $FF $EF $43 $BC $FF $0F $05 $FA $FF $8F $4B $74 $FF $5F $B1 $AE $7F $2B $9A $95 $7F
; Tile index $087
.db $FF $7F $80 $FF $FB $FF $00 $FF $FF $FE $00 $FF $FE $FF $01 $FE $FC $FC $03 $FE $FD $FE $02 $FC $F9 $7C $82 $FC $FE $75 $89 $FE
; Tile index $088
.db $1E $3F $C1 $80 $5E $B5 $8B $01 $BC $7F $83 $03 $BC $7B $07 $03 $3A $FD $07 $07 $39 $D6 $2F $07 $04 $7B $8F $0F $13 $EC $EF $5F
; Tile index $089
.db $01 $F8 $FE $BF $8A $73 $F4 $DF $05 $F9 $FE $EF $08 $F6 $F7 $FF $06 $79 $F9 $FF $45 $BA $FA $FF $85 $56 $FA $FF $72 $9F $E5 $FF
; Tile index $08A
.db $00 $A2 $00 $FF $00 $85 $00 $FF $60 $5F $8A $FF $E5 $80 $7F $FF $1B $80 $FF $FF $47 $C0 $BF $FF $2F $E0 $5F $FF $DF $DF $20 $FF
; Tile index $08B
.db $01 $FF $00 $FF $40 $BF $00 $FF $20 $F0 $9F $FF $60 $00 $FF $FF $FC $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $A0 $A0 $5F $FF
; Tile index $08C
.db $DA $DA $25 $FF $AF $FF $00 $FF $01 $00 $FF $FF $81 $86 $7E $FF $0F $31 $F1 $FF $82 $5D $FD $FE $C1 $0E $FE $FF $00 $00 $FF $FF
; Tile index $08D
.db $04 $04 $FB $FF $DF $FF $00 $FF $7F $00 $FF $FF $21 $F0 $DF $FF $9D $60 $E3 $1F $80 $FE $FF $8B $EA $35 $75 $AF $60 $74 $9F $FF
; Tile index $08E
.db $40 $00 $FF $FF $FA $FA $05 $FF $FE $00 $FF $FF $78 $21 $DF $FF $F1 $02 $FE $FF $FF $00 $FF $FF $FE $01 $FF $FF $7D $03 $FE $FE
; Tile index $08F
.db $E6 $1F $F8 $F0 $A1 $7F $E0 $E0 $CF $BF $C0 $80 $2F $DF $E0 $C0 $AF $7F $C0 $80 $0F $FB $84 $00 $BF $FF $00 $00 $BF $FF $00 $00
; Tile index $090
.db $FE $FF $00 $00 $BF $FF $00 $00 $D5 $FF $00 $00 $EF $FF $00 $00 $DB $FF $00 $00 $F7 $FF $00 $00 $DF $FF $00 $00 $FF $FF $00 $00
; Tile index $091
.db $DF $FF $00 $00 $77 $FF $00 $00 $7F $FF $00 $00 $B7 $FF $00 $00 $BF $FF $00 $00 $7F $FF $00 $00 $F5 $FF $00 $00 $FE $FF $00 $00
; Tile index $092
.db $FF $FF $10 $10 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $04 $04 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $093
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $10 $10 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $80 $FF $FF $00 $00
; Tile index $094
.db $FF $DF $21 $01 $FF $FB $84 $80 $FF $FF $00 $00 $FF $FE $01 $00 $FF $FF $00 $00 $FF $FF $08 $08 $FF $FF $40 $40 $FF $FF $00 $00
; Tile index $095
.db $5C $9F $E0 $FF $5F $6F $F0 $7F $07 $D0 $3F $0F $C2 $B7 $4D $03 $F0 $FF $00 $00 $ED $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $096
.db $BD $FF $00 $FF $FE $FF $00 $FF $FF $AD $52 $FF $4A $FF $00 $FF $5D $FF $00 $00 $00 $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $097
.db $20 $FF $00 $FF $E4 $FF $00 $FF $FF $6F $90 $FF $55 $FF $00 $FF $AF $FF $00 $00 $02 $FB $04 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $098
.db $00 $FE $00 $FF $00 $FB $00 $FF $FB $FB $04 $FF $2A $D5 $00 $FF $F7 $F7 $08 $00 $BA $BA $45 $00 $FF $FF $00 $00 $FF $EF $10 $00
; Tile index $099
.db $00 $A0 $00 $FF $00 $DC $00 $FF $02 $FF $20 $FF $15 $EA $80 $FF $6D $6D $92 $00 $D5 $D5 $2A $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $09A
.db $23 $73 $1C $FF $39 $5D $26 $FF $4B $8B $B4 $FF $63 $8F $18 $FF $21 $17 $DE $0F $41 $4F $B4 $0F $EA $F9 $0C $0F $F3 $F4 $0C $07
; Tile index $09B
.db $EA $7F $80 $FF $F5 $FF $00 $FF $EB $BF $40 $FF $F3 $FF $00 $FF $F5 $FF $00 $FF $FB $7F $00 $FF $9E $FF $00 $FF $1E $FF $00 $FF
; Tile index $09C
.db $DD $00 $21 $7E $9E $63 $42 $FF $E1 $DB $00 $FF $9F $63 $80 $FF $02 $FE $00 $FF $04 $B6 $00 $FF $00 $4D $00 $FF $00 $48 $00 $FF
; Tile index $09D
.db $4E $F9 $04 $FF $8F $FC $00 $FF $1B $FC $04 $FB $15 $F2 $06 $F9 $3E $B1 $0B $F0 $2F $E4 $0F $F0 $37 $7A $1E $E0 $4A $61 $09 $F4
; Tile index $09E
.db $D3 $6A $ED $5F $DA $26 $65 $9F $F5 $0B $38 $C7 $E5 $03 $00 $FF $50 $60 $00 $FF $40 $70 $00 $FF $48 $FE $00 $FF $10 $FF $00 $FF
; Tile index $09F
.db $EB $C0 $3F $FF $F8 $20 $DF $FF $FE $DE $21 $FF $FD $E1 $1E $FF $01 $2F $00 $FF $00 $2F $00 $FF $01 $BF $00 $FF $2F $FF $00 $FF
; Tile index $0A0
.db $80 $1E $FF $FF $04 $0F $FB $FF $0B $0F $F4 $FF $34 $36 $CB $FF $BB $BB $44 $FF $FC $FC $03 $FF $AF $7F $80 $FF $2D $FD $02 $FF
; Tile index $0A1
.db $60 $38 $C0 $FF $70 $3C $C0 $FF $74 $7F $80 $FF $54 $7F $80 $FF $DF $FF $00 $FF $AF $FF $00 $FF $58 $FC $03 $FF $5C $FD $03 $FE
; Tile index $0A2
.db $00 $05 $00 $FF $00 $17 $00 $FF $00 $7F $00 $FF $83 $FF $00 $FF $6F $03 $FD $81 $80 $5E $21 $80 $AF $7F $80 $00 $0B $FF $00 $00
; Tile index $0A3
.db $00 $6F $00 $FF $03 $FF $00 $FF $AB $EB $14 $FF $F4 $F4 $0B $FF $FF $E0 $5F $40 $0D $FF $00 $00 $FF $FF $00 $00 $F5 $FF $00 $00
; Tile index $0A4
.db $AB $FF $00 $FF $FF $FF $00 $FF $AA $AA $55 $FF $A9 $A9 $56 $FF $FF $89 $77 $01 $50 $FF $00 $00 $EE $FF $00 $00 $F5 $FF $00 $00
; Tile index $0A5
.db $BD $BD $42 $FF $EA $EA $15 $FF $82 $80 $7F $FF $53 $50 $AD $FE $F8 $93 $6C $00 $48 $FF $00 $00 $FF $FF $00 $00 $5E $FF $00 $00
; Tile index $0A6
.db $27 $9F $FC $FC $B1 $1F $D0 $F0 $C7 $7F $40 $C0 $47 $BF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0A7
.db $FF $FF $00 $00 $FF $7F $80 $00 $FF $FF $00 $00 $FE $FF $00 $00 $EB $FF $00 $00 $F7 $FF $00 $00 $DF $FF $00 $00 $EF $FF $00 $00
; Tile index $0A8
.db $FF $FF $00 $00 $FF $FF $00 $00 $BD $FF $00 $00 $F7 $FF $00 $00 $EF $FF $00 $00 $7A $FF $00 $00 $AF $FF $00 $00 $7F $FF $00 $00
; Tile index $0A9
.db $7F $FF $00 $00 $DF $FF $00 $00 $F7 $FF $00 $00 $7F $FF $00 $00 $FF $FF $00 $00 $EF $FF $00 $00 $BB $FF $00 $00 $FF $FF $00 $00
; Tile index $0AA
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $F7 $08 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $88 $88
; Tile index $0AB
.db $FF $FF $00 $00 $FF $DF $20 $00 $FF $FF $01 $01 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $80 $FF $FF $00 $00 $FF $FF $20 $20
; Tile index $0AC
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $08 $08 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $01
; Tile index $0AD
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $01 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $10 $10 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0AE
.db $F5 $FE $06 $07 $F3 $F8 $04 $03 $FA $FD $03 $01 $FD $FC $02 $01 $FD $EE $11 $00 $FC $FD $02 $00 $FE $FF $00 $00 $FF $FF $00 $00
; Tile index $0AF
.db $0C $FE $00 $FF $44 $0D $00 $FF $01 $01 $01 $FE $02 $42 $42 $BD $AE $2E $2E $D1 $EB $6B $6B $D4 $FF $3F $BF $40 $BF $7F $7F $00
; Tile index $0B0
.db $00 $10 $00 $FF $00 $00 $00 $FF $08 $08 $08 $F7 $44 $44 $44 $BB $94 $94 $94 $6B $A8 $A8 $A8 $57 $3D $3D $3D $C2 $7B $7B $7B $84
; Tile index $0B1
.db $16 $D2 $16 $E9 $85 $81 $04 $FB $54 $D7 $54 $AB $08 $0A $08 $F7 $50 $54 $50 $AF $D0 $D0 $D0 $2F $60 $60 $60 $9F $E0 $E0 $E0 $1F
; Tile index $0B2
.db $17 $BF $00 $FF $03 $FF $00 $FF $06 $7F $00 $FF $03 $FE $01 $FE $0E $5C $01 $FE $0F $DC $02 $FC $0C $3B $00 $FC $0C $69 $02 $F8
; Tile index $0B3
.db $C5 $F7 $74 $8F $FE $01 $80 $03 $1C $73 $85 $02 $84 $70 $08 $07 $CB $DE $2F $08 $4B $F5 $07 $08 $FF $97 $57 $18 $DF $CA $2F $10
; Tile index $0B4
.db $06 $FF $00 $FF $A4 $1F $00 $FF $00 $0F $00 $FF $08 $5F $40 $BF $40 $5A $40 $BF $80 $13 $80 $7F $C0 $4B $C0 $3F $C0 $E5 $C0 $3F
; Tile index $0B5
.db $BC $FC $03 $FE $5E $FD $00 $FE $34 $F6 $09 $FC $3A $FD $04 $F8 $79 $FB $04 $F8 $34 $FB $08 $F0 $63 $F7 $08 $F0 $73 $FF $10 $F0
; Tile index $0B6
.db $7F $FF $00 $00 $7F $FF $00 $00 $BF $BF $40 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0B7
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $EF $EF $10 $00
; Tile index $0B8
.db $BF $FF $00 $00 $AE $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $F5 $FF $00 $00 $F9 $FF $00 $00
; Tile index $0B9
.db $BD $FF $00 $00 $FF $FF $00 $00 $ED $FF $00 $00 $FF $FF $00 $00 $FD $FF $00 $00 $FB $FF $00 $00 $6F $FF $00 $00 $7D $FF $00 $00
; Tile index $0BA
.db $F5 $FF $00 $00 $DB $FF $00 $00 $7F $FF $00 $00 $ED $FF $00 $00 $7E $FF $00 $00 $AF $FF $00 $00 $B7 $FF $00 $00 $FB $FF $00 $00
; Tile index $0BB
.db $6D $FF $00 $00 $FB $FF $00 $00 $AD $FF $00 $00 $F7 $FF $00 $00 $BE $FF $00 $00 $DB $FF $00 $00 $77 $FF $00 $00 $BA $FF $00 $00
; Tile index $0BC
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $04 $04 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0BD
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $22 $22
; Tile index $0BE
.db $FF $FF $04 $04 $FF $FF $00 $00 $FF $FF $80 $80 $FF $FF $10 $10 $FF $FF $01 $01 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $10 $10
; Tile index $0BF
.db $FF $FF $00 $00 $FF $FF $40 $40 $FF $FF $00 $00 $FF $FF $08 $08 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $04 $04
; Tile index $0C0
.db $FF $FF $00 $00 $FF $FF $80 $80 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $04 $04 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0C1
.db $FE $0E $5E $21 $3E $7E $BE $01 $FF $DF $3F $10 $CF $DB $3B $00 $CF $CF $3F $00 $EB $F3 $0B $04 $CF $F7 $0F $04 $E7 $E0 $1B $00
; Tile index $0C2
.db $F2 $F2 $F2 $0D $F7 $F7 $F7 $08 $FF $FF $FF $00 $EF $EF $EF $10 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $0C3
.db $CC $CC $CC $33 $CA $CA $CA $35 $DE $DE $DE $21 $B5 $B5 $B5 $4A $BF $BF $BF $40 $7D $7D $7D $82 $FE $FE $FE $01 $F5 $F5 $F5 $0A
; Tile index $0C4
.db $1B $33 $04 $F8 $0F $33 $08 $F0 $23 $2F $00 $F0 $1A $27 $10 $E0 $1A $2C $23 $C0 $3D $46 $09 $C0 $0B $AD $11 $C1 $4B $3C $02 $81
; Tile index $0C5
.db $3B $6B $AB $14 $FF $8D $5F $20 $DF $57 $5F $60 $BE $54 $FE $01 $FE $56 $FE $01 $7E $32 $7E $81 $FC $EC $FC $03 $FD $55 $FD $02
; Tile index $0C6
.db $80 $2B $00 $7F $80 $C7 $80 $7F $00 $0B $00 $FF $00 $07 $00 $FF $01 $0B $00 $FF $81 $87 $80 $7F $02 $0F $00 $FF $03 $0A $01 $FE
; Tile index $0C7
.db $E7 $EF $10 $E0 $F7 $EF $20 $E0 $CF $CF $30 $C0 $CF $BF $40 $80 $3F $BB $C4 $80 $EF $3F $80 $00 $7F $BF $40 $00 $BF $7F $00 $00
; Tile index $0C8
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FE $01 $00 $FF $FF $40 $40 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0C9
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $DF $20 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0CA
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FD $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0CB
.db $FF $FF $00 $00 $7F $FF $00 $00 $FF $FF $00 $00 $DF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $BB $FF $00 $00 $FD $FF $00 $00
; Tile index $0CC
.db $FF $FF $00 $00 $FF $FF $00 $00 $EF $FF $00 $00 $FE $FF $00 $00 $FF $FF $00 $00 $7F $FF $00 $00 $FF $FF $00 $00 $FE $FF $00 $00
; Tile index $0CD
.db $F7 $FF $00 $00 $BF $FF $00 $00 $F2 $FF $00 $00 $DF $FF $00 $00 $EF $FF $00 $00 $BD $FF $00 $00 $7A $FF $00 $00 $D7 $FF $00 $00
; Tile index $0CE
.db $F6 $FF $00 $00 $DD $FF $00 $00 $FE $FF $00 $00 $FF $FF $00 $00 $FE $FF $00 $00 $BD $FF $00 $00 $EB $FF $00 $00 $FD $FF $00 $00
; Tile index $0CF
.db $EF $FF $00 $00 $BF $FF $00 $00 $D5 $FF $00 $00 $BF $FF $00 $00 $ED $FF $00 $00 $B6 $FF $00 $00 $AB $FF $00 $00 $6B $FF $00 $00
; Tile index $0D0
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $01 $FF $FF $10 $10 $FF $FF $00 $00 $FF $FF $02 $02 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0D1
.db $FF $FF $80 $80 $FF $FF $00 $00 $FF $FF $10 $10 $FF $FF $00 $00 $FF $FF $04 $04 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0D2
.db $FF $FF $00 $00 $FF $FF $80 $80 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $40 $40
; Tile index $0D3
.db $F3 $FC $00 $00 $F8 $BC $43 $00 $FD $FC $03 $00 $FF $FC $01 $00 $FD $FF $00 $00 $FC $FD $02 $00 $FE $FF $00 $00 $FF $FF $00 $00
; Tile index $0D4
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $BF $BF $00 $FF $FF $FF $00 $FF $BF $BF $00 $FF $7F $FF $00 $FF $3F $7F $00 $7F $3F $FF $00
; Tile index $0D5
.db $FC $FC $FC $03 $F8 $F8 $F8 $07 $F5 $F4 $F5 $0A $F9 $F8 $F8 $06 $F2 $F0 $F3 $0C $F0 $F0 $F3 $0C $E4 $E3 $E4 $18 $E5 $E1 $E2 $18
; Tile index $0D6
.db $D3 $B7 $8B $80 $75 $30 $8D $02 $2F $D7 $27 $04 $0B $73 $8B $04 $7F $CB $0F $00 $17 $C7 $37 $08 $3F $8F $5F $00 $6F $CF $2F $10
; Tile index $0D7
.db $FA $FA $FA $05 $FD $DD $FD $02 $F5 $F5 $F5 $0A $FE $FE $FE $01 $FE $FE $FE $01 $FA $BA $BA $05 $DE $DE $DE $21 $FC $FC $FC $03
; Tile index $0D8
.db $86 $8C $81 $7E $03 $0C $02 $FC $08 $1B $00 $FC $0C $09 $06 $F8 $15 $3B $08 $F0 $05 $33 $08 $F0 $37 $2A $15 $E0 $31 $27 $08 $E0
; Tile index $0D9
.db $FF $FF $00 $00 $7F $EF $10 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $04 $04 $FF $FF $00 $00 $FF $FF $20 $20
; Tile index $0DA
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $02 $02 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $40 $40 $FF $FF $00 $00
; Tile index $0DB
.db $FF $FF $00 $00 $FF $FF $00 $00 $FB $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0DC
.db $FD $FF $00 $00 $7F $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $DE $FF $00 $00 $EF $FF $00 $00 $7F $FF $00 $00 $FF $FF $00 $00
; Tile index $0DD
.db $6E $FF $00 $00 $DD $FF $00 $00 $B6 $FF $00 $00 $EF $FF $00 $00 $DD $FF $00 $00 $D5 $FF $00 $00 $F7 $FF $00 $00 $BA $FF $00 $00
; Tile index $0DE
.db $9D $FF $00 $00 $AF $FF $00 $00 $BB $FF $00 $00 $6D $FF $00 $00 $FB $FF $00 $00 $57 $FF $00 $00 $55 $FF $00 $00 $AE $FF $00 $00
; Tile index $0DF
.db $B7 $FF $00 $00 $5A $FF $00 $00 $D7 $FF $00 $00 $5A $FF $00 $00 $F7 $FF $00 $00 $6D $FF $00 $00 $4B $FF $00 $00 $EA $FF $00 $00
; Tile index $0E0
.db $FF $FF $00 $00 $FF $FF $01 $01 $FF $FF $10 $10 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $01 $FF $FF $40 $40 $FF $FF $00 $00
; Tile index $0E1
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $10 $10 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $10 $10
; Tile index $0E2
.db $FF $FF $21 $21 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $20 $20 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0E3
.db $FF $FF $10 $10 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $02 $02 $FF $FF $00 $00 $FF $FF $10 $10 $FF $FF $80 $80
; Tile index $0E4
.db $FF $FF $00 $00 $FF $FF $04 $04 $FF $FF $40 $40 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $08 $08 $FF $FF $00 $00
; Tile index $0E5
.db $FF $FF $01 $01 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $80 $FF $FF $08 $08 $FF $FF $00 $00
; Tile index $0E6
.db $3F $5F $BF $00 $3F $DF $1F $00 $93 $B3 $4F $00 $C3 $F4 $09 $00 $FD $FF $00 $00 $FD $FF $00 $00 $CF $FF $00 $00 $CF $EF $10 $00
; Tile index $0E7
.db $CF $C3 $C8 $30 $D3 $D7 $D8 $20 $74 $4D $52 $A0 $B0 $AF $A0 $60 $E0 $BC $43 $00 $17 $7C $81 $00 $F2 $F0 $0C $01 $F3 $FE $03 $00
; Tile index $0E8
.db $7F $3F $BF $00 $7F $6F $FF $40 $FF $7F $7F $00 $BF $3F $BF $40 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $0E9
.db $FA $FA $FA $05 $FC $FC $FC $03 $FC $FC $FC $03 $F8 $F8 $F8 $07 $FC $FD $FC $03 $F6 $F6 $F4 $0B $F9 $FA $F9 $06 $F1 $F0 $F0 $0E
; Tile index $0EA
.db $6F $4F $30 $C0 $27 $8F $30 $C0 $CF $BF $40 $80 $4F $9F $20 $80 $FF $3F $80 $00 $BF $7F $00 $00 $7F $FD $02 $00 $3F $FF $00 $00
; Tile index $0EB
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $01 $FF $FF $00 $00 $FF $FF $20 $20
; Tile index $0EC
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FE $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0ED
.db $FE $FF $00 $00 $FF $FF $00 $00 $7F $FF $00 $00 $FD $FF $00 $00 $D7 $FF $00 $00 $F7 $FF $00 $00 $DB $FF $00 $00 $69 $FF $00 $00
; Tile index $0EE
.db $EF $FF $00 $00 $FF $FF $00 $00 $AF $FF $00 $00 $F5 $FF $00 $00 $57 $FF $00 $00 $7D $FF $00 $00 $57 $FF $00 $00 $FE $FF $00 $00
; Tile index $0EF
.db $F5 $FF $00 $00 $5A $FF $00 $00 $6D $FF $00 $00 $DE $FF $00 $00 $BD $FF $00 $00 $6B $FF $00 $00 $AF $FF $00 $00 $FB $FF $00 $00
; Tile index $0F0
.db $9B $FF $00 $00 $ED $FF $00 $00 $AB $FF $00 $00 $D7 $FF $00 $00 $BF $FF $00 $00 $6B $FF $00 $00 $6E $FF $00 $00 $BD $FF $00 $00
; Tile index $0F1
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $80 $80 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $01
; Tile index $0F2
.db $73 $F3 $0F $00 $BF $F7 $07 $04 $C7 $E6 $1E $00 $CF $DF $2F $04 $AF $CF $1F $00 $FF $CF $1F $00 $1F $9F $7F $00 $3F $6F $BF $00
; Tile index $0F3
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $0F4
.db $F0 $F3 $F0 $0C $F4 $F6 $F5 $08 $E1 $E3 $E4 $18 $EC $EB $E8 $10 $C3 $C3 $CC $30 $DF $C3 $C0 $20 $D7 $CF $C0 $20 $F7 $C7 $E8 $00
; Tile index $0F5
.db $FF $FF $00 $00 $FE $FF $00 $00 $FF $FF $00 $00 $FF $F6 $09 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0F6
.db $FF $FF $00 $00 $FF $FF $00 $00 $F7 $FF $00 $00 $FE $FF $00 $00 $BF $FF $00 $00 $F7 $FF $00 $00 $D7 $FF $00 $00 $BF $FF $00 $00
; Tile index $0F7
.db $B7 $FF $00 $00 $FD $FF $00 $00 $75 $FF $00 $00 $DF $FF $00 $00 $B5 $FF $00 $00 $FF $FF $00 $00 $7D $FF $00 $00 $DF $FF $00 $00
; Tile index $0F8
.db $AB $FF $00 $00 $6D $FF $00 $00 $B5 $FF $00 $00 $6F $FF $00 $00 $FD $FF $00 $00 $7B $FF $00 $00 $FF $FF $00 $00 $5B $FF $00 $00
; Tile index $0F9
.db $D7 $FF $00 $00 $5A $FF $00 $00 $AF $FF $00 $00 $7A $FF $00 $00 $EF $FF $00 $00 $5A $FF $00 $00 $ED $FF $00 $00 $77 $FF $00 $00
; Tile index $0FA
.db $F7 $FF $00 $00 $AD $FF $00 $00 $75 $FF $00 $00 $FF $FF $00 $00 $55 $FF $00 $00 $D7 $FF $00 $00 $ED $FF $00 $00 $76 $FF $00 $00
; Tile index $0FB
.db $9F $CB $3B $00 $BF $9F $5F $00 $CF $C7 $37 $00 $CF $CF $3F $00 $DB $F3 $07 $00 $FF $F7 $07 $00 $F6 $F4 $0B $00 $E0 $F8 $07 $00
; Tile index $0FC
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FD $FD $FD $02 $FE $FE $FF $00 $FE $FE $FF $02 $FD $FC $FE $00
; Tile index $0FD
.db $4F $4F $70 $80 $EF $9F $C0 $00 $4F $3F $00 $80 $57 $1F $A0 $00 $77 $7F $80 $00 $BB $BF $40 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $0FE
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FE $FF $00 $00 $FF $FF $00 $00
; Tile index $0FF
.db $FB $FF $00 $00 $DE $FF $00 $00 $FF $FF $00 $00 $F7 $FF $00 $00 $DD $FF $00 $00 $FF $FF $00 $00 $FD $FF $00 $00 $EF $FF $00 $00
; Tile index $100
.db $F5 $FF $00 $00 $FF $FF $00 $00 $EF $FF $00 $00 $7F $FF $00 $00 $DA $FF $00 $00 $7F $FF $00 $00 $F6 $FF $00 $00 $7F $FF $00 $00
; Tile index $101
.db $FF $FF $00 $00 $FF $FF $00 $00 $F5 $FF $00 $00 $FE $FF $00 $00 $DB $FF $00 $00 $FE $FF $00 $00 $A5 $FF $00 $00 $DD $FF $00 $00
; Tile index $102
.db $FF $FF $00 $00 $76 $FF $00 $00 $DF $FF $00 $00 $EA $FF $00 $00 $B7 $FF $00 $00 $D9 $FF $00 $00 $56 $FF $00 $00 $6D $FF $00 $00
; Tile index $103
.db $DD $FF $00 $00 $BB $FF $00 $00 $ED $FF $00 $00 $BB $FF $00 $00 $D6 $FF $00 $00 $55 $FF $00 $00 $AA $FF $00 $00 $D6 $FF $00 $00
; Tile index $104
.db $AB $FF $00 $00 $6A $FF $00 $00 $55 $FF $00 $00 $55 $FF $00 $00 $95 $FF $00 $00 $55 $FF $00 $00 $AA $FF $00 $00 $A4 $FF $00 $00
; Tile index $105
.db $9C $FC $03 $00 $BC $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FB $FF $00 $00
; Tile index $106
.db $B4 $04 $57 $0C $31 $81 $4E $00 $EB $FB $04 $00 $F2 $FF $00 $00 $FC $FF $00 $00 $7E $FF $00 $00 $DF $FF $00 $00 $FF $FF $00 $00
; Tile index $107
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $EF $FF $00 $00 $BF $FF $00 $00 $EF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $108
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FD $FF $00 $00 $F7 $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FD $FF $00 $00
; Tile index $109
.db $FF $FF $00 $00 $F7 $FF $00 $00 $7F $FF $00 $00 $FD $FF $00 $00 $D7 $FF $00 $00 $FD $FF $00 $00 $EF $FF $00 $00 $7B $FF $00 $00
; Tile index $10A
.db $FF $FF $00 $00 $FF $FF $00 $00 $7F $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $EF $FF $00 $00 $BE $FF $00 $00 $FF $FF $00 $00
; Tile index $10B
.db $FF $FF $00 $00 $FE $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $7F $FF $00 $00 $F7 $FF $00 $00 $FF $FF $00 $00 $FD $FF $00 $00
; Tile index $10C
.db $DD $FF $00 $00 $F6 $FF $00 $00 $DB $FF $00 $00 $FE $FF $00 $00 $5B $FF $00 $00 $FE $FF $00 $00 $DB $FF $00 $00 $FF $FF $00 $00
; Tile index $10D
.db $EB $FF $00 $00 $FF $FF $00 $00 $DD $FF $00 $00 $F7 $FF $00 $00 $AD $FF $00 $00 $FB $FF $00 $00 $EF $FF $00 $00 $BB $FF $00 $00
; Tile index $10E
.db $75 $FF $00 $00 $5E $FF $00 $00 $ED $FF $00 $00 $76 $FF $00 $00 $DF $FF $00 $00 $F5 $FF $00 $00 $7E $FF $00 $00 $DF $FF $00 $00
; Tile index $10F
.db $DA $FF $00 $00 $EB $FF $00 $00 $AA $FF $00 $00 $DA $FF $00 $00 $55 $FF $00 $00 $AB $FF $00 $00 $F6 $FF $00 $00 $4A $FF $00 $00
; Tile index $110
.db $B5 $FF $00 $00 $5B $FF $00 $00 $D6 $FF $00 $00 $AA $FF $00 $00 $55 $FF $00 $00 $5A $FF $00 $00 $D7 $FF $00 $00 $BD $FF $00 $00
; Tile index $111
.db $29 $FF $00 $00 $B6 $FF $00 $00 $A9 $FF $00 $00 $D5 $FF $00 $00 $A9 $FF $00 $00 $AA $FF $00 $00 $29 $FF $00 $00 $4A $FF $00 $00
; Tile index $112
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $01 $00 $00 $00 $00 $00 $00 $00
; Tile index $113
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FD $FF $00 $00 $FF $FF $00 $00 $FE $FF $00 $00
; Tile index $114
.db $FF $FF $00 $00 $F5 $FF $00 $00 $BF $FF $00 $00 $FF $FF $00 $00 $FD $FF $00 $00 $AF $FF $00 $00 $DC $FF $00 $00 $AB $FF $00 $00
; Tile index $115
.db $EF $FF $00 $00 $FF $FF $00 $00 $DB $FF $00 $00 $FF $FF $00 $00 $DF $FF $00 $00 $BF $FF $00 $00 $FE $FF $00 $00 $A5 $FF $00 $00
; Tile index $116
.db $FF $FF $00 $00 $DE $FF $00 $00 $FF $FF $00 $00 $BB $FF $00 $00 $FF $FF $00 $00 $FB $FF $00 $00 $DF $FF $00 $00 $FF $FF $00 $00
; Tile index $117
.db $DF $FF $00 $00 $FB $FF $00 $00 $FF $FF $00 $00 $BD $FF $00 $00 $EF $FF $00 $00 $7A $FF $00 $00 $FF $FF $00 $00 $DB $FF $00 $00
; Tile index $118
.db $B6 $FF $00 $00 $7B $FF $00 $00 $D6 $FF $00 $00 $FA $FF $00 $00 $FD $FF $00 $00 $DE $FF $00 $00 $FB $FF $00 $00 $DF $FF $00 $00
; Tile index $119
.db $F6 $FF $00 $00 $AD $FF $00 $00 $DB $FF $00 $00 $ED $FF $00 $00 $AB $FF $00 $00 $DD $FF $00 $00 $B6 $FF $00 $00 $6D $FF $00 $00
; Tile index $11A
.db $A5 $FF $00 $00 $DA $FF $00 $00 $6B $FF $00 $00 $7D $FF $00 $00 $D5 $FF $00 $00 $7B $FF $00 $00 $D5 $FF $00 $00 $AA $FF $00 $00
; Tile index $11B
.db $B5 $FF $00 $00 $AA $FF $00 $00 $5A $FF $00 $00 $AB $FF $00 $00 $5A $FF $00 $00 $AB $FF $00 $00 $56 $FF $00 $00 $DA $FF $00 $00
; Tile index $11C
.db $EB $FF $00 $00 $AD $FF $00 $00 $D7 $FF $00 $00 $6F $FF $00 $00 $DD $FF $00 $00 $ED $FF $00 $00 $52 $FF $00 $00 $FC $FF $00 $00
; Tile index $11D
.db $57 $FF $00 $00 $AA $FF $00 $00 $49 $FF $00 $00 $6A $FF $00 $00 $55 $FF $00 $00 $4A $FF $00 $00 $A5 $FF $00 $00 $95 $FF $00 $00
; Tile index $11E
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FD $FF $00 $00 $FF $FF $00 $00 $FB $FF $00 $00
; Tile index $11F
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $AF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $DF $FF $00 $00 $FF $FF $00 $00
; Tile index $120
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $BF $FF $00 $00 $FF $FF $00 $00 $BF $FF $00 $00
; Tile index $121
.db $FF $FF $00 $00 $FF $FF $00 $00 $F7 $FF $00 $00 $FE $FF $00 $00 $FF $FF $00 $00 $BD $FF $00 $00 $FB $FF $00 $00 $6E $FF $00 $00
; Tile index $122
.db $F7 $FF $00 $00 $7F $FF $00 $00 $FD $FF $00 $00 $DF $FF $00 $00 $FD $FF $00 $00 $F7 $FF $00 $00 $DD $FF $00 $00 $6F $FF $00 $00
; Tile index $123
.db $FF $FF $00 $00 $6D $FF $00 $00 $7E $FF $00 $00 $DF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $7B $FF $00 $00 $EF $FF $00 $00
; Tile index $124
.db $FF $FF $00 $00 $AA $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FD $FF $00 $00 $FF $FF $00 $00 $7F $FF $00 $00
; Tile index $125
.db $B6 $FF $00 $00 $FF $FF $00 $00 $6D $FF $00 $00 $F7 $FF $00 $00 $DF $FF $00 $00 $F7 $FF $00 $00 $DA $FF $00 $00 $6F $FF $00 $00
; Tile index $126
.db $EE $FF $00 $00 $FF $FF $00 $00 $BA $FF $00 $00 $EF $FF $00 $00 $7B $FF $00 $00 $DF $FF $00 $00 $B6 $FF $00 $00 $6D $FF $00 $00
; Tile index $127
.db $FB $FF $00 $00 $BF $FF $00 $00 $FB $FF $00 $00 $DF $FF $00 $00 $7F $FF $00 $00 $ED $FF $00 $00 $FE $FF $00 $00 $DF $FF $00 $00
; Tile index $128
.db $F6 $FF $00 $00 $57 $FF $00 $00 $FD $FF $00 $00 $6B $FF $00 $00 $FF $FF $00 $00 $B6 $FF $00 $00 $FB $FF $00 $00 $AE $FF $00 $00
; Tile index $129
.db $FF $FF $00 $00 $6A $FF $00 $00 $FF $FF $00 $00 $B7 $FF $00 $00 $FF $FF $00 $00 $DB $FF $00 $00 $FD $FF $00 $00 $B7 $FF $00 $00
; Tile index $12A
.db $EF $FF $00 $00 $BB $FF $00 $00 $6D $FF $00 $00 $DE $FF $00 $00 $75 $FF $00 $00 $FF $FF $00 $00 $AA $FF $00 $00 $7D $FF $00 $00
; Tile index $12B
.db $D3 $FF $00 $00 $55 $FF $00 $00 $ED $FF $00 $00 $AA $FF $00 $00 $D6 $FF $00 $00 $6A $FF $00 $00 $DB $FF $00 $00 $AA $FF $00 $00
; Tile index $12C
.db $6B $FF $00 $00 $AA $FF $00 $00 $55 $FF $00 $00 $A4 $FF $00 $00 $A9 $FF $00 $00 $C5 $FF $00 $00 $52 $FF $00 $00 $D5 $FF $00 $00
; Tile index $12D
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FE $FF $00 $00 $DB $FF $00 $00 $FF $FF $00 $00 $F7 $FF $00 $00 $FF $FF $00 $00
; Tile index $12E
.db $FF $FF $00 $00 $FF $FF $00 $00 $DF $FF $00 $00 $F7 $FF $00 $00 $FF $FF $00 $00 $7F $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $12F
.db $FF $FF $00 $00 $FF $FF $00 $00 $FE $FF $00 $00 $FB $FF $00 $00 $EF $FF $00 $00 $FF $FF $00 $00 $FB $FF $00 $00 $EF $FF $00 $00
; Tile index $130
.db $DD $FF $00 $00 $FA $FF $00 $00 $F7 $FF $00 $00 $EF $FF $00 $00 $75 $FF $00 $00 $EE $FF $00 $00 $29 $FF $00 $00 $D6 $FF $00 $00
; Tile index $131
.db $B5 $FF $00 $00 $FF $FF $00 $00 $7F $FF $00 $00 $FB $FF $00 $00 $57 $FF $00 $00 $FD $FF $00 $00 $A6 $FF $00 $00 $BB $FF $00 $00
; Tile index $132
.db $FF $FF $00 $00 $FF $FF $00 $00 $7F $FF $00 $00 $D6 $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $133
.db $FF $FF $00 $00 $FF $FF $00 $00 $FE $FF $00 $00 $D7 $FF $00 $00 $FE $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $134
.db $FF $FF $00 $00 $FF $FF $00 $00 $EB $FF $00 $00 $BE $FF $00 $00 $F7 $FF $00 $00 $BF $FF $00 $00 $FF $FF $00 $00 $76 $FF $00 $00
; Tile index $135
.db $FF $FF $00 $00 $FF $FF $00 $00 $F6 $FF $00 $00 $DD $FF $00 $00 $FF $FF $00 $00 $FE $FF $00 $00 $FB $FF $00 $00 $EF $FF $00 $00
; Tile index $136
.db $FB $FF $00 $00 $BF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $F5 $FF $00 $00 $BF $FF $00 $00 $D2 $FF $00 $00 $5D $FF $00 $00
; Tile index $137
.db $7B $FF $00 $00 $F6 $FF $00 $00 $BF $FF $00 $00 $FF $FF $00 $00 $EF $FF $00 $00 $7A $FF $00 $00 $EB $FF $00 $00 $B5 $FF $00 $00
; Tile index $138
.db $D5 $FF $00 $00 $FD $FF $00 $00 $FF $FF $00 $00 $57 $FF $00 $00 $D5 $FF $00 $00 $B5 $FF $00 $00 $6A $FF $00 $00 $95 $FF $00 $00
; Tile index $139
.db $AB $FF $00 $00 $D4 $FF $00 $00 $7F $FF $00 $00 $B5 $FF $00 $00 $55 $FF $00 $00 $D6 $FF $00 $00 $29 $FF $00 $00 $AD $FF $00 $00
; Tile index $13A
.db $57 $FF $00 $00 $AA $FF $00 $00 $FE $FF $00 $00 $2F $FF $00 $00 $5A $FF $00 $00 $FB $FF $00 $00 $04 $FF $00 $00 $6B $FF $00 $00
; Tile index $13B
.db $B5 $FF $00 $00 $AA $FF $00 $00 $FF $FF $00 $00 $4A $FF $00 $00 $AB $FF $00 $00 $57 $FF $00 $00 $51 $FF $00 $00 $89 $FF $00 $00
